from django.db import models


# Create your models here.


class t_certification_GAP_t1(models.Model): # GAP main table
    Application_No = models.CharField(max_length=30, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    Certificate_Type = models.CharField(max_length=50, default=None)
    Application_Type = models.CharField(max_length=50, default=None)
    CID = models.BigIntegerField(blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.IntegerField(default=None, blank=True, null=True)
    Gewog_Code = models.IntegerField(default=None, blank=True, null=True)
    Village_Code = models.IntegerField(default=None, blank=True, null=True)
    Present_Address = models.CharField(max_length=250, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Farmer_Group_No = models.CharField(max_length=100, blank=True, null=True)
    Farmer_Group_Name = models.CharField(max_length=200, blank=True, null=True)
    Pack_House = models.CharField(max_length=1, blank=True, null=True)
    Crop_Production = models.CharField(max_length=1, blank=True, null=True)
    Proposed_Standard = models.TextField(blank=True, null=True)
    Terms_Bafra_Certification = models.CharField(max_length=1, blank=True, null=True)
    Terms_Change_Willingness = models.CharField(max_length=1, blank=True, null=True)
    Terms_Abide = models.CharField(max_length=1, blank=True, null=True)
    Terms_Agreement = models.CharField(max_length=1, blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Audit_Team_Leader = models.CharField(max_length=100, blank=True, null=True)
    Audit_Team_Acceptance = models.CharField(max_length=1, blank=True, null=True)
    Audit_Team_Acceptance_Remarks = models.TextField(blank=True, null=True)
    Audit_Plan_Date = models.DateField(blank=True, null=True)
    Audit_Plan_Criteria = models.TextField(blank=True, null=True)
    Audit_Plan_Type = models.CharField(max_length=200, blank=True, null=True)
    Audit_Plan_Scope = models.TextField(blank=True, null=True)
    Audit_Plan_Acceptance = models.CharField(max_length=1, blank=True, null=True)
    Audit_Plan_Acceptance_Remarks = models.TextField(blank=True, null=True)
    Audit_Findings_Site_History = models.TextField(blank=True, null=True)
    Audit_Findings_Water_Source = models.TextField(blank=True, null=True)
    Audit_Findings_Product_Quality = models.TextField(blank=True, null=True)
    Audit_Findings_Harvesting = models.TextField(blank=True, null=True)
    Audit_Findings_Equipment = models.TextField(blank=True, null=True)
    Audit_Findings_Manufacturing_Production = models.TextField(blank=True, null=True)
    Audit_Findings_Sampling_Testing = models.TextField(blank=True, null=True)
    Audit_Findings_Packing_Marking = models.TextField(blank=True, null=True)
    Audit_Findings_Storage_Transport = models.TextField(blank=True, null=True)
    Audit_Findings_Traceability = models.TextField(blank=True, null=True)
    Audit_Findings_Worker_Health = models.TextField(blank=True, null=True)
    Audit_Findings_Group_Requirement = models.TextField(blank=True, null=True)
    Audit_Findings_Others = models.TextField(blank=True, null=True)
    Feasibility_Inspection_Date = models.DateField(blank=True, null=True)
    Feasibility_Inspection_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Feasibility_Inspection_Remarks = models.TextField(blank=True, null=True)
    Factory_Inspection_Date = models.DateField(blank=True, null=True)
    Factory_Inspection_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Factory_Inspection_Remarks = models.TextField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Certificate_No = models.CharField(max_length=100, blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)

class t_certification_GAP_t2(models.Model): # GAP certification farmer group
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    CID = models.CharField(max_length=100, default=None, blank=True, null=True)
    Name = models.CharField(max_length=100, default=None, blank=True, null=True)

class t_certification_GAP_t3(models.Model): # GAP Certification audit team
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Login_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Name = models.CharField(max_length=100, default=None, blank=True, null=True)

class t_certification_GAP_t4(models.Model): # GAP Certification crop production
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Crop_Name = models.CharField(max_length=100, default=None, blank=True, null=True)
    Area_Cultivated = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=50)
    P_From_Date = models.DateField(blank=True, null=True)
    P_To_Date = models.DateField(blank=True, null=True)
    P_Yield = models.IntegerField(blank=True, null=True)
    P_Yield_Unit = models.CharField(max_length=50)
    P_Harvest_Month = models.CharField(max_length=50)
    P_Sold = models.IntegerField(blank=True, null=True)
    P_Sold_Unit = models.CharField(max_length=50)
    P_Balance_Stock = models.IntegerField(blank=True, null=True)
    C_From_Date = models.DateField(blank=True, null=True)
    C_To_Date = models.DateField(blank=True, null=True)
    C_Estimated_Yield = models.IntegerField(blank=True, null=True)
    C_Yield_Unit = models.CharField(max_length=50)
    C_Harvest_Month = models.CharField(max_length=50)

class t_certification_GAP_t5(models.Model): # GAP Certification pack house
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Pack_House_Name = models.CharField(max_length=200, blank=True, null=True)
    Pack_House_Address = models.TextField(blank=True, null=True)
    Processing_Type = models.CharField(max_length=200, blank=True, null=True)
    P_From_Date = models.DateField(blank=True, null=True)
    P_To_Date = models.DateField(blank=True, null=True)
    P_Production = models.IntegerField(blank=True, null=True)
    P_Production_Unit = models.CharField(max_length=50)
    P_Sold = models.IntegerField(blank=True, null=True)
    P_Balance_Stock = models.IntegerField(blank=True, null=True)
    C_From_Date = models.DateField(blank=True, null=True)
    C_To_Date = models.DateField(blank=True, null=True)
    C_Production = models.IntegerField(blank=True, null=True)
    C_Sold = models.IntegerField(blank=True, null=True)
    C_Balance_Stock = models.IntegerField(blank=True, null=True)


class t_certification_GAP_t6(models.Model): # GAP Certification Audit Plan
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Audit_Plan_Date = models.DateField(blank=True, null=True)
    Audit_Plan_Time = models.TimeField(blank=True, null=True)
    Area_Function_Department = models.TextField(blank=True, null=True)
    Company_Contact = models.TextField(blank=True, null=True)

class t_certification_GAP_t7(models.Model): # Audit Finding/Report (Farm inputs/raw materials and packaging materials)
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Audit_Findings_Farm_Inputs = models.CharField(max_length=200, blank=True, null=True)
    Audit_Findings_Farm_Supplier = models.CharField(max_length=200, blank=True, null=True)
    Audit_Findings_Farm_Invoice = models.CharField(max_length=200, blank=True, null=True)

class t_certification_GAP_t8(models.Model): # GAP Observation.
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Inspection_Type = models.CharField(max_length=200, blank=True, null=True)
    Clause_Number = models.CharField(max_length=200, blank=True, null=True)
    Non_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Non_Conformity_Category = models.CharField(max_length=1, blank=True, null=True)
    Non_Conformity_Description = models.CharField(max_length=1, blank=True, null=True)
    Corrective_Action_Proposed_Auditee = models.TextField(blank=True, null=True)
    Corrective_Action_Taken_Auditee = models.TextField(blank=True, null=True)
    Corrective_Action_Date = models.DateField(blank=True, null=True)
    Corrective_Action_Verified_Auditor = models.TextField(blank=True, null=True)
    Non_Conformity_Closure = models.CharField(max_length=1, blank=True, null=True)


# Organic Certification
class t_certification_Organic_t1(models.Model): # Organic Certification main table
    Application_No = models.CharField(max_length=30, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    Certificate_Type = models.CharField(max_length=50, default=None)
    Application_Type = models.CharField(max_length=50, default=None)
    CID = models.BigIntegerField(blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.IntegerField(default=None, blank=True, null=True)
    Gewog_Code = models.IntegerField(default=None, blank=True, null=True)
    Village_Code = models.IntegerField(default=None, blank=True, null=True)
    Present_Address = models.CharField(max_length=250, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Farmer_Group_No = models.CharField(max_length=100, blank=True, null=True)
    Farmer_Group_Name = models.CharField(max_length=200, blank=True, null=True)
    Crop_Production = models.CharField(max_length=1, blank=True, null=True)
    Wild_Collection = models.CharField(max_length=1, blank=True, null=True)
    Animal_Husbandry = models.CharField(max_length=1, blank=True, null=True)
    Aquaculture = models.CharField(max_length=1, blank=True, null=True)
    Apiculture = models.CharField(max_length=1, blank=True, null=True)
    Processing_Unit = models.CharField(max_length=1, blank=True, null=True)
    Proposed_Standard = models.TextField(blank=True, null=True)
    Terms_Bafra_Certification = models.CharField(max_length=1, blank=True, null=True)
    Terms_Change_Willingness = models.CharField(max_length=1, blank=True, null=True)
    Terms_Abide = models.CharField(max_length=1, blank=True, null=True)
    Terms_Agreement = models.CharField(max_length=1, blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Audit_Team_Leader = models.CharField(max_length=100, blank=True, null=True)
    Audit_Team_Acceptance = models.CharField(max_length=1, blank=True, null=True)
    Audit_Team_Acceptance_Remarks = models.TextField(blank=True, null=True)
    Audit_Plan_Date = models.DateField(blank=True, null=True)
    Audit_Plan_Criteria = models.TextField(blank=True, null=True)
    Audit_Plan_Type = models.CharField(max_length=200, blank=True, null=True)
    Audit_Plan_Scope = models.TextField(blank=True, null=True)
    Audit_Plan_Acceptance = models.CharField(max_length=1, blank=True, null=True)
    Audit_Plan_Acceptance_Remarks = models.TextField(blank=True, null=True)
    Audit_Findings_Site_History = models.TextField(blank=True, null=True)
    Audit_Findings_Water_Source = models.TextField(blank=True, null=True)
    Audit_Findings_Product_Quality = models.TextField(blank=True, null=True)
    Audit_Findings_Harvesting = models.TextField(blank=True, null=True)
    Audit_Findings_Equipment = models.TextField(blank=True, null=True)
    Audit_Findings_Manufacturing_Production = models.TextField(blank=True, null=True)
    Audit_Findings_Sampling_Testing = models.TextField(blank=True, null=True)
    Audit_Findings_Packing_Marking = models.TextField(blank=True, null=True)
    Audit_Findings_Storage_Transport = models.TextField(blank=True, null=True)
    Audit_Findings_Traceability = models.TextField(blank=True, null=True)
    Audit_Findings_Worker_Health = models.TextField(blank=True, null=True)
    Audit_Findings_Group_Requirement = models.TextField(blank=True, null=True)
    Audit_Findings_Others = models.TextField(blank=True, null=True)
    Feasibility_Inspection_Date = models.DateField(blank=True, null=True)
    Feasibility_Inspection_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Feasibility_Inspection_Remarks = models.TextField(blank=True, null=True)
    Factory_Inspection_Date = models.DateField(blank=True, null=True)
    Factory_Inspection_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Factory_Inspection_Remarks = models.TextField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Certificate_No = models.CharField(max_length=100, blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)

class t_certification_Organic_t2(models.Model): # Organic Certification farmer group
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    CID = models.CharField(max_length=100, default=None, blank=True, null=True)
    Name = models.CharField(max_length=100, default=None, blank=True, null=True)

class t_certification_Organic_t3(models.Model): # Organic Certification audit team
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Login_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Name = models.CharField(max_length=100, default=None, blank=True, null=True)

class t_certification_Organic_t4(models.Model): # Organic Certification crop production
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Crop_Name = models.CharField(max_length=100, default=None, blank=True, null=True)
    Area_Cultivated = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=50)
    P_From_Date = models.DateField(blank=True, null=True)
    P_To_Date = models.DateField(blank=True, null=True)
    P_Yield = models.IntegerField(blank=True, null=True)
    P_Yield_Unit = models.CharField(max_length=50)
    P_Harvest_Month = models.CharField(max_length=50)
    P_Sold = models.IntegerField(blank=True, null=True)
    P_Sold_Unit = models.CharField(max_length=50)
    P_Balance_Stock = models.IntegerField(blank=True, null=True)
    C_From_Date = models.DateField(blank=True, null=True)
    C_To_Date = models.DateField(blank=True, null=True)
    C_Estimated_Yield = models.IntegerField(blank=True, null=True)
    C_Yield_Unit = models.CharField(max_length=50)
    C_Harvest_Month = models.CharField(max_length=50)

class t_certification_Organic_t5(models.Model): # Organic Certification processing unit
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Production_House_Name = models.CharField(max_length=200, blank=True, null=True)
    Production_House_Address = models.TextField(blank=True, null=True)
    Processing_Type = models.CharField(max_length=200, blank=True, null=True)
    P_From_Date = models.DateField(blank=True, null=True)
    P_To_Date = models.DateField(blank=True, null=True)
    P_Production = models.IntegerField(blank=True, null=True)
    P_Production_Unit = models.CharField(max_length=50)
    P_Sold = models.IntegerField(blank=True, null=True)
    P_Balance_Stock = models.IntegerField(blank=True, null=True)
    C_From_Date = models.DateField(blank=True, null=True)
    C_To_Date = models.DateField(blank=True, null=True)
    C_Production = models.IntegerField(blank=True, null=True)
    C_Sold = models.IntegerField(blank=True, null=True)
    C_Balance_Stock = models.IntegerField(blank=True, null=True)

class t_certification_Organic_t6(models.Model):  # Organic Certification Wild Collection
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Common_Name = models.CharField(max_length=200, default=None, blank=True, null=True)
    Botanical_Name = models.CharField(max_length=200, default=None, blank=True, null=True)
    Plant_Part = models.CharField(max_length=200, default=None, blank=True, null=True)
    Estimated_Harvest = models.IntegerField(default=None, blank=True, null=True)
    Harvest_Unit = models.CharField(max_length=50, default=None, blank=True, null=True)
    Harvest_Season = models.CharField(max_length=200, default=None, blank=True, null=True)
    Harvest_Acreage = models.IntegerField(default=None, blank=True, null=True)
    Acreage_Unit = models.CharField(max_length=50, default=None, blank=True, null=True)

class t_certification_Organic_t7(models.Model):  # Organic Certification Animal Husbandry/Livestock
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Livestock_Type = models.CharField(max_length=100, default=None, blank=True, null=True)
    Male_no = models.IntegerField(default=None, blank=True, null=True)
    Female_no = models.IntegerField(default=None, blank=True, null=True)
    Estimated_Production = models.IntegerField(default=None, blank=True, null=True)
    Production_Unit = models.CharField(max_length=50, default=None, blank=True, null=True)
    Production_Sold = models.CharField(max_length=200, default=None, blank=True, null=True)

class t_certification_Organic_t7(models.Model):  # Organic Certification Aquaculture
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Aquaculture_Type = models.CharField(max_length=100, default=None, blank=True, null=True)
    Estimated_Yield = models.IntegerField(default=None, blank=True, null=True)
    Yield_Unit = models.CharField(max_length=50, default=None, blank=True, null=True)
    Harvest_Month = models.CharField(max_length=200, default=None, blank=True, null=True)
    Harvest_Sold = models.IntegerField(default=None, blank=True, null=True)
    Harvest_Unit = models.CharField(max_length=50, default=None, blank=True, null=True)
    Balance_Stock = models.IntegerField(default=None, blank=True, null=True)

class t_certification_Organic_t8(models.Model):  # Organic Certification Apiculture
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Common_Name = models.CharField(max_length=200, default=None, blank=True, null=True)
    Botanical_Name = models.CharField(max_length=200, default=None, blank=True, null=True)
    Estimated_Harvest = models.IntegerField(default=None, blank=True, null=True)
    Harvest_Unit = models.CharField(max_length=50, default=None, blank=True, null=True)
    Harvest_Acreage = models.IntegerField(default=None, blank=True, null=True)
    Acreage_Unit = models.CharField(max_length=50, default=None, blank=True, null=True)

class t_certification_Organic_t9(models.Model): # Organic Certification Audit Plan
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Audit_Plan_Date = models.DateField(blank=True, null=True)
    Audit_Plan_Time = models.TimeField(blank=True, null=True)
    Area_Function_Department = models.TextField(blank=True, null=True)
    Company_Contact = models.TextField(blank=True, null=True)

class t_certification_Organic_t10(models.Model): # Organic Certification Audit Finding/Report Related to T1)
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Audit_Findings_Farm_Inputs = models.CharField(max_length=200, blank=True, null=True)
    Audit_Findings_Farm_Supplier = models.CharField(max_length=200, blank=True, null=True)
    Audit_Findings_Farm_Invoice = models.CharField(max_length=200, blank=True, null=True)

class t_certification_Organic_t11(models.Model): # Organic Certification Observation.
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Inspection_Type = models.CharField(max_length=200, blank=True, null=True)
    Clause_Number = models.CharField(max_length=200, blank=True, null=True)
    Non_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Non_Conformity_Category = models.CharField(max_length=1, blank=True, null=True)
    Non_Conformity_Description = models.CharField(max_length=1, blank=True, null=True)
    Corrective_Action_Proposed_Auditee = models.TextField(blank=True, null=True)
    Corrective_Action_Taken_Auditee = models.TextField(blank=True, null=True)
    Corrective_Action_Date = models.DateField(blank=True, null=True)
    Corrective_Action_Verified_Auditor = models.TextField(blank=True, null=True)
    Non_Conformity_Closure = models.CharField(max_length=1, blank=True, null=True)



# Food Product Certificate

class t_certification_Food_t1(models.Model): # Food Product main table
    Application_No = models.CharField(max_length=30, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    Firm_Name = models.CharField(max_length=250, blank=True, null=True)
    Firm_Address = models.TextField(blank=True, null=True)
    Firm_Contact_No = models.IntegerField(blank=True, null=True)
    Firm_Email = models.EmailField(blank=True, null=True)
    Factory_Name = models.CharField(max_length=250, blank=True, null=True)
    Factory_Address = models.TextField(blank=True, null=True)
    Factory_Contact_No = models.IntegerField(blank=True, null=True)
    Factory_Email = models.EmailField(blank=True, null=True)
    Product_Description = models.TextField(blank=True, null=True)
    Product_Trade_Mark = models.TextField(blank=True, null=True)
    P_From_Date = models.DateField(blank=True, null=True)
    P_To_Date = models.DateField(blank=True, null=True)
    P_Production = models.IntegerField(blank=True, null=True)
    P_Production_Unit = models.CharField(max_length=50, blank=True, null=True)
    P_Production_Value = models.IntegerField(blank=True, null=True)
    P_Export = models.IntegerField(blank=True, null=True)
    P_Export_Unit = models.CharField(max_length=50, blank=True, null=True)
    C_From_Date = models.DateField(blank=True, null=True)
    C_To_Date = models.DateField(blank=True, null=True)
    C_Production = models.IntegerField(blank=True, null=True)
    C_Production_Unit = models.CharField(max_length=50, blank=True, null=True)
    C_Production_Value = models.IntegerField(blank=True, null=True)
    C_Export = models.IntegerField(blank=True, null=True)
    C_Export_Unit = models.CharField(max_length=50, blank=True, null=True)
    Proposed_Standard = models.TextField(blank=True, null=True)
    Terms_Bafra_Certification = models.CharField(max_length=1, blank=True, null=True)
    Terms_Change_Willingness = models.CharField(max_length=1, blank=True, null=True)
    Terms_Abide = models.CharField(max_length=1, blank=True, null=True)
    Terms_Agreement = models.CharField(max_length=1, blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Audit_Team_Leader = models.CharField(max_length=100, blank=True, null=True)
    Audit_Team_Acceptance = models.CharField(max_length=1, blank=True, null=True)
    Audit_Team_Acceptance_Remarks = models.TextField(blank=True, null=True)
    Audit_Plan_Date = models.DateField(blank=True, null=True)
    Audit_Plan_Criteria = models.TextField(blank=True, null=True)
    Audit_Plan_Type = models.CharField(max_length=200, blank=True, null=True)
    Audit_Plan_Scope = models.TextField(blank=True, null=True)
    Audit_Plan_Acceptance = models.CharField(max_length=1, blank=True, null=True)
    Audit_Plan_Acceptance_Remarks = models.TextField(blank=True, null=True)
    Audit_Findings_Site_History = models.TextField(blank=True, null=True)
    Audit_Findings_Water_Source = models.TextField(blank=True, null=True)
    Audit_Findings_Product_Quality = models.TextField(blank=True, null=True)
    Audit_Findings_Harvesting = models.TextField(blank=True, null=True)
    Audit_Findings_Equipment = models.TextField(blank=True, null=True)
    Audit_Findings_Manufacturing_Production = models.TextField(blank=True, null=True)
    Audit_Findings_Sampling_Testing = models.TextField(blank=True, null=True)
    Audit_Findings_Packing_Marking = models.TextField(blank=True, null=True)
    Audit_Findings_Storage_Transport = models.TextField(blank=True, null=True)
    Audit_Findings_Traceability = models.TextField(blank=True, null=True)
    Audit_Findings_Worker_Health = models.TextField(blank=True, null=True)
    Audit_Findings_Group_Requirement = models.TextField(blank=True, null=True)
    Audit_Findings_Others = models.TextField(blank=True, null=True)
    Feasibility_Inspection_Date = models.DateField(blank=True, null=True)
    Feasibility_Inspection_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Feasibility_Inspection_Remarks = models.TextField(blank=True, null=True)
    Factory_Inspection_Date = models.DateField(blank=True, null=True)
    Factory_Inspection_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Factory_Inspection_Remarks = models.TextField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Certificate_No = models.CharField(max_length=100, blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)

class t_certification_Food_t2(models.Model): # Food Product farmer group
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    CID = models.CharField(max_length=100, default=None, blank=True, null=True)
    Name = models.CharField(max_length=100, default=None, blank=True, null=True)

class t_certification_Food_t3(models.Model): # Food Product audit team
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Login_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Name = models.CharField(max_length=100, default=None, blank=True, null=True)

class t_certification_Food_t4(models.Model): # Food Product Audit Plan
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Audit_Plan_Date = models.DateField(blank=True, null=True)
    Audit_Plan_Time = models.TimeField(blank=True, null=True)
    Area_Function_Department = models.TextField(blank=True, null=True)
    Company_Contact = models.TextField(blank=True, null=True)

class t_certification_Food_t5(models.Model): # Food Product Audit Finding/Report (Farm inputs/raw materials)
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Audit_Findings_Farm_Inputs = models.CharField(max_length=200, blank=True, null=True)
    Audit_Findings_Farm_Supplier = models.CharField(max_length=200, blank=True, null=True)
    Audit_Findings_Farm_Invoice = models.CharField(max_length=200, blank=True, null=True)

class t_certification_Food_t6(models.Model): # Food Product Observation.
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=20)
    Inspection_Type = models.CharField(max_length=200, blank=True, null=True)
    Clause_Number = models.CharField(max_length=200, blank=True, null=True)
    Non_Conformity = models.CharField(max_length=1, blank=True, null=True)
    Non_Conformity_Category = models.CharField(max_length=1, blank=True, null=True)
    Non_Conformity_Description = models.CharField(max_length=1, blank=True, null=True)
    Corrective_Action_Proposed_Auditee = models.TextField(blank=True, null=True)
    Corrective_Action_Taken_Auditee = models.TextField(blank=True, null=True)
    Corrective_Action_Date = models.DateField(blank=True, null=True)
    Corrective_Action_Verified_Auditor = models.TextField(blank=True, null=True)
    Non_Conformity_Closure = models.CharField(max_length=1, blank=True, null=True)

