from django.db import models


# Create your models here.
class t_food_export_certificate_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Exporters_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Exporters_Address = models.TextField(blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Importer_Name = models.CharField(max_length=250, blank=True, null=True)
    Importer_Address = models.TextField(blank=True, null=True)
    Importing_Country = models.IntegerField(default=None, blank=True, null=True)
    Product_Name = models.CharField(max_length=250, blank=True, null=True)
    No_Of_Packages = models.IntegerField(blank=True, null=True)
    Description_Of_Packages = models.TextField(blank=True, null=True)
    Quantity = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=100, blank=True, null=True)
    Declared_Point_of_Exit = models.IntegerField(blank=True, null=True)
    Export_Expected_Date = models.DateField(blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Purpose_Of_Export = models.TextField(blank=True, null=True)
    Consignment_Location_Dzongkhag = models.IntegerField(blank=True, null=True)
    Consignment_Location_Gewog = models.IntegerField(blank=True, null=True)
    Consignment_Location = models.CharField(max_length=100, blank=True, null=True)
    Additional_Information = models.TextField(default=None, blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspection_Leader = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Team = models.TextField(blank=True, null=True)
    Inspection_Remarks = models.TextField(blank=True, null=True)
    Quantity_Certified = models.IntegerField(blank=True, null=True)
    Unit_Certified = models.CharField(max_length=100, blank=True, null=True)
    Quantity_Rejected = models.IntegerField(blank=True, null=True)
    Unit_Rejected = models.CharField(max_length=100, blank=True, null=True)
    Export_Permit_No = models.CharField(max_length=50, blank=True, null=True)
    Approved_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Rejection_Reason = models.TextField(blank=True, null=True)
    Terms = models.TextField(blank=True, null=True)


class t_food_licensing_food_handler_t1(models.Model):
    Application_No = models.CharField(max_length=100, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    Nationality = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Permit_No = models.CharField(max_length=100, blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Country_Code = models.IntegerField(default=None, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Training_Request = models.CharField(max_length=250, blank=True, null=True)
    Preferred_Inspection_Place = models.TextField(blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Associated_Food_Establishment = models.TextField(blank=True, null=True)
    Training_Batch_No = models.CharField(max_length=100, blank=True, null=True)
    Training_From_Date = models.DateField(blank=True, null=True)
    Training_To_Date = models.DateField(blank=True, null=True)
    License_Status = models.CharField(max_length=100, blank=True, null=True)
    Assessment_Score = models.IntegerField(blank=True, null=True)
    Minimum_Score = models.IntegerField(blank=True, null=True)
    Trainer = models.CharField(max_length=100, blank=True, null=True)
    FH_License_No = models.CharField(max_length=50, blank=True, null=True)
    Approved_Date = models.DateField(blank=True, null=True)
    FH_License_Validity_Period = models.IntegerField(blank=True, null=True)
    FH_License_Validity = models.DateField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    OIC_Remarks = models.TextField(default=None, blank=True, null=True)
    Inspection_Remarks = models.TextField(default=None, blank=True, null=True)
    Attendance = models.CharField(max_length=5, default=None, blank=True, null=True)
    Training_Venue = models.CharField(max_length=100, default=None, blank=True, null=True)
    Training_Batch = models.CharField(max_length=100, default=None, blank=True, null=True)
    App_Status = models.CharField(max_length=5, default=None, blank=True, null=True)


class t_food_import_permit_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Import_Type = models.CharField(max_length=50, default=None)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Present_Address = models.CharField(max_length=250, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Operation_Type = models.CharField(max_length=100, blank=True, null=True)
    Origin_Country_Food = models.CharField(max_length=250, blank=True, null=True)
    Transit_Country = models.CharField(max_length=5)
    Country_Of_Transit = models.CharField(max_length=100)
    Means_of_Conveyance = models.TextField(blank=True, null=True)
    Place_Of_Entry = models.IntegerField(blank=True, null=True)
    Final_Destination = models.CharField(max_length=250, blank=True, null=True)
    Expected_Arrival_Date = models.DateField(blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Application_Date = models.DateField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    Import_Permit_No = models.CharField(max_length=50, blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Terms = models.TextField(blank=True, null=True)


class t_food_import_permit_t2(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=50)
    Common_Name = models.CharField(max_length=100, blank=True, null=True)
    Product_Category = models.CharField(max_length=100, blank=True, null=True)
    Product_Characteristics = models.CharField(max_length=250, blank=True, null=True)
    Quantity = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=10)
    Exporter_Type = models.CharField(max_length=100, blank=True, null=True)
    Quantity_Balance = models.IntegerField(blank=True, null=True)
    Remarks = models.TextField(blank=True, null=True)


class t_food_import_permit_inspection_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Import_Type = models.CharField(max_length=50, default=None)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Present_Address = models.CharField(max_length=250, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Operation_Type = models.CharField(max_length=100, blank=True, null=True)
    Origin_Country_Food = models.TextField(blank=True, null=True)
    Transit_Country = models.CharField(max_length=5)
    Country_Of_Transit = models.CharField(max_length=100)
    Means_of_Conveyance = models.TextField(blank=True, null=True)
    Place_Of_Entry = models.IntegerField(blank=True, null=True)
    Final_Destination = models.CharField(max_length=250, blank=True, null=True)
    Expected_Arrival_Date = models.DateField(blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Application_Date = models.DateField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    Import_Permit_No = models.CharField(max_length=50, blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Actual_Point_Of_Entry = models.IntegerField(blank=True, null=True)
    Inspection_Request_Remarks = models.TextField(blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspection_Type = models.CharField(max_length=250, blank=True, null=True)
    Inspection_Time = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Leader = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Team = models.TextField(blank=True, null=True)
    Clearance_Ref_No = models.CharField(max_length=50, blank=True, null=True)
    Inspection_Remarks = models.TextField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Terms = models.TextField(blank=True, null=True)


class t_food_import_permit_inspection_t2(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=50)
    Common_Name = models.CharField(max_length=100, blank=True, null=True)
    Product_Category = models.CharField(max_length=100, blank=True, null=True)
    Product_Characteristics = models.CharField(max_length=250, blank=True, null=True)
    Quantity = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=10)
    Exporter_Type = models.CharField(max_length=100, blank=True, null=True)
    Quantity_Released = models.IntegerField(blank=True, null=True)
    Remarks = models.TextField(blank=True, null=True)
    Quantity_Balance = models.IntegerField(blank=True, null=True)
    Quantity_Balance_1 = models.IntegerField(blank=True, null=True)
    Product_Record_Id = models.IntegerField(blank=True, null=True)


class t_food_import_permit_inspection_t3(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=50)
    Current_Observation = models.TextField(blank=True, null=True)
    Decision_Conformity = models.TextField(blank=True, null=True)


class t_food_business_registration_licensing_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Application_Date = models.DateField()
    Applicant_Id = models.CharField(max_length=30, default=None, blank=True, null=True)
    Business_Name = models.CharField(max_length=30, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Name_Owner = models.CharField(max_length=30, blank=True, null=True)
    Contact_No = models.IntegerField()
    Email = models.CharField(max_length=30, blank=True, null=True)
    Address = models.CharField(max_length=250, blank=True, null=True)
    Name_Manager = models.CharField(max_length=100, blank=True, null=True)
    License_Criteria = models.CharField(max_length=100, blank=True, null=True)
    Product_Category = models.TextField(blank=True, null=True)
    Product = models.TextField(blank=True, null=True)
    Current_Status = models.CharField(max_length=250, blank=True, null=True)
    Years_In_Production = models.IntegerField(default=None, blank=True, null=True)
    Volume_Last_Year = models.CharField(max_length=100, blank=True, null=True)
    Volume_Unit = models.CharField(max_length=10, default=None, blank=True, null=True)
    Project_Proposal = models.CharField(max_length=5, blank=True, null=True)
    Water_Source = models.CharField(max_length=100, blank=True, null=True)
    Site_History = models.CharField(max_length=100, blank=True, null=True)
    Previous_Business = models.CharField(max_length=250, blank=True, null=True)
    Process_Outsource = models.CharField(max_length=10, blank=True, null=True)
    Legal_Entity = models.CharField(max_length=100, blank=True, null=True)
    Large_Corporation = models.CharField(max_length=10, blank=True, null=True)
    Large_Corporation_Relation = models.CharField(max_length=100, blank=True, null=True)
    FBO_License_Status = models.CharField(max_length=100, blank=True, null=True)
    FBO_License_No = models.CharField(max_length=100, blank=True, null=True)
    Invalid_Reason = models.TextField(blank=True, null=True)
    FBO_Judicial_Proceedings = models.CharField(max_length=100, blank=True, null=True)
    Judicial_Proceedings_Details = models.CharField(max_length=100, blank=True, null=True)
    FBO_Regulatory_Proceedings = models.CharField(max_length=100, blank=True, null=True)
    Regulatory_Proceedings_Details = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Type = models.CharField(max_length=100, blank=True, null=True)
    Desired_FI_Inspection_Date = models.DateField(blank=True, null=True)
    Desired_FR_Inspection_Date = models.DateField(blank=True, null=True)
    FB_License_No = models.CharField(max_length=100, blank=True, null=True)  # System Generated FB License No
    FI_Inspection_Date = models.DateField(blank=True, null=True)
    FI_Inspection_Leader = models.CharField(max_length=100, blank=True, null=True)
    FI_Response = models.TextField(blank=True, null=True)
    FI_Recommendation = models.TextField(blank=True, null=True)
    FR_Inspection_Date = models.DateField(blank=True, null=True)
    FR_Inspection_Leader = models.CharField(max_length=100, blank=True, null=True)
    FR_Response = models.TextField(blank=True, null=True)
    FR_Recommendation = models.TextField(blank=True, null=True)
    Field_Office_Id = models.IntegerField(default=None, blank=True, null=True)
    Conditional_Clearance_No = models.CharField(max_length=100, blank=True, null=True)
    Clearance_Approve_Date = models.DateField(blank=True, null=True)
    Clearance_Validity_Period = models.IntegerField(blank=True, null=True)
    Clearance_Validity = models.DateField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    FR_Inspection_Team = models.CharField(max_length=100, default=None, blank=True, null=True)
    FI_Inspection_Team = models.CharField(max_length=100, default=None, blank=True, null=True)
    Dzongkhag_Code = models.IntegerField(default=None, blank=True, null=True)
    Gewog_Code = models.IntegerField(default=None, blank=True, null=True)
    Village_Code = models.IntegerField(default=None, blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Process_Flow_Technology = models.TextField(blank=True, null=True)
    Quality_Assurance_System = models.TextField(blank=True, null=True)


class t_food_business_registration_licensing_t2(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=30)
    BP_Outsourced_To = models.CharField(max_length=100)
    Contact_No = models.IntegerField(default=None)
    Address = models.TextField()
    BAFRA_License_No = models.CharField(max_length=100, blank=True, null=True)


class t_food_business_registration_licensing_t3(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=30)
    FH_License_No = models.CharField(max_length=30)
    FH_Name = models.CharField(max_length=100)


class t_food_business_registration_licensing_t4(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=30)
    Meeting_Type = models.CharField(max_length=100)
    Name = models.CharField(max_length=30)
    Designation = models.CharField(max_length=30)
    Meeting_Date = models.DateField()
    Type = models.CharField(max_length=100, default=None, blank=True, null=True)


class t_food_business_registration_licensing_t5(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=30)
    Inspection_Type = models.CharField(max_length=100)
    Requirement = models.TextField()
    Observation = models.TextField(default=None, blank=True, null=True)
    Clause_No = models.CharField(max_length=100, default=None, blank=True, null=True)
    Concern = models.CharField(max_length=10, default=None, blank=True, null=True)
    Date = models.DateField(default=None, blank=True, null=True)
    FBO_Response = models.TextField(default=None, blank=True, null=True)
    NC = models.CharField(max_length=10, default=None, blank=True, null=True)
    NC_Category = models.CharField(max_length=10, default=None, blank=True, null=True)


class t_food_business_registration_licensing_t6(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=30)
    Meeting_Type = models.CharField(max_length=100)
    Name = models.CharField(max_length=30)
    Designation = models.CharField(max_length=30)


class t_food_business_registration_licensing_t7(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=30)
    Name = models.CharField(max_length=100)
    Source_Country = models.CharField(max_length=30)


class t_food_business_registration_licensing_t8(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=30)
    Name = models.CharField(max_length=100)
    Source_Country = models.CharField(max_length=30)
