from django.db import models


# Create your models here.
class t_food_export_certificate_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Exporters_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.IntegerField(default=None, blank=True, null=True)
    Gewog_Code = models.IntegerField(default=None, blank=True, null=True)
    Village_Code = models.IntegerField(default=None, blank=True, null=True)
    Exporters_Address = models.TextField(blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Importer_Name = models.CharField(max_length=250, blank=True, null=True)
    Importer_Address = models.TextField(blank=True, null=True)
    Importing_Country = models.IntegerField(default=None, blank=True, null=True)
    Product_Name = models.CharField(max_length=250, blank=True, null=True)
    No_Of_Packages = models.IntegerField(blank=True, null=True)
    Description_Of_Packages = models.TextField(blank=True, null=True)
    Quantity = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=100, blank=True, null=True)
    Declared_Point_of_Exit = models.IntegerField(blank=True, null=True)
    Export_Expected_Date = models.DateField(blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Purpose_Of_Export = models.TextField(blank=True, null=True)
    Consignment_Location_Dzongkhag = models.IntegerField(blank=True, null=True)
    Consignment_Location_Gewog = models.IntegerField(blank=True, null=True)
    Consignment_Location = models.CharField(max_length=100, blank=True, null=True)
    Additional_Information = models.TextField(default=None, blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspection_Leader = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Team = models.TextField(blank=True, null=True)
    Inspection_Remarks = models.TextField(blank=True, null=True)
    Quantity_Certified = models.IntegerField(blank=True, null=True)
    Unit_Certified = models.CharField(max_length=100, blank=True, null=True)
    Quantity_Rejected = models.IntegerField(blank=True, null=True)
    Unit_Rejected = models.CharField(max_length=100, blank=True, null=True)
    Export_Permit_No = models.CharField(max_length=20, blank=True, null=True)
    Approved_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100)


class t_food_licensinf_food_handler_t1(models.Model):
    Application_No = models.CharField(max_length=100, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    Nationality = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Permit_No = models.CharField(max_length=100, blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.IntegerField(default=None, blank=True, null=True)
    Gewog_Code = models.IntegerField(default=None, blank=True, null=True)
    Village_Code = models.IntegerField(default=None, blank=True, null=True)
    Country_Code = models.IntegerField(default=None, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Training_Request = models.CharField(max_length=250, blank=True, null=True)
    Preferred_Inspection_Place = models.TextField(blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Associated_Food_Establishment = models.TextField(blank=True, null=True)
    Training_Batch_No = models.CharField(max_length=100, blank=True, null=True)
    Training_From_Date = models.DateField(blank=True, null=True)
    Training_To_Date = models.DateField(blank=True, null=True)
    License_Status = models.CharField(max_length=100, blank=True, null=True)
    Assessment_Score = models.IntegerField(blank=True, null=True)
    Minimum_Score = models.IntegerField(blank=True, null=True)
    Trainer = models.CharField(max_length=100, blank=True, null=True)
    FH_License_No = models.CharField(max_length=20, blank=True, null=True)
    Approved_Date = models.DateField(blank=True, null=True)
    FH_License_Validity_Period = models.IntegerField(blank=True, null=True)
    FH_License_Validity = models.DateField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100)
    OIC_Remarks = models.TextField(default=None, blank=True, null=True)
    Inspection_Remarks = models.TextField(default=None, blank=True, null=True)
    Attendance = models.CharField(max_length=5, default='No', blank=True, null=True)