from django.db import models


# Create your models here.
class t_food_export_certificate_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Application_Type = models.CharField(max_length=1, blank=True, null=True)
    Application_Date = models.DateField(blank=True, null=True)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Exporters_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Exporters_Address = models.TextField(blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Importer_Name = models.CharField(max_length=250, blank=True, null=True)
    Importer_Address = models.TextField(blank=True, null=True)
    Importing_Country = models.IntegerField(default=None, blank=True, null=True)
    Product_Name = models.CharField(max_length=250, blank=True, null=True)
    No_Of_Packages = models.IntegerField(blank=True, null=True)
    Description_Of_Packages = models.TextField(blank=True, null=True)
    Quantity = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=100, blank=True, null=True)
    Declared_Point_of_Exit = models.IntegerField(blank=True, null=True)
    Export_Expected_Date = models.DateField(blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Purpose_Of_Export = models.TextField(blank=True, null=True)
    Consignment_Location_Dzongkhag = models.IntegerField(blank=True, null=True)
    Consignment_Location_Gewog = models.IntegerField(blank=True, null=True)
    Consignment_Location = models.CharField(max_length=100, blank=True, null=True)
    Additional_Information = models.TextField(default=None, blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspection_Leader = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Team = models.TextField(blank=True, null=True)
    Inspection_Remarks = models.TextField(blank=True, null=True)
    Quantity_Certified = models.IntegerField(blank=True, null=True)
    Unit_Certified = models.CharField(max_length=100, blank=True, null=True)
    Quantity_Rejected = models.IntegerField(blank=True, null=True)
    Unit_Rejected = models.CharField(max_length=100, blank=True, null=True)
    Export_Permit_No = models.CharField(max_length=50, blank=True, null=True)
    Approved_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Rejection_Reason = models.TextField(blank=True, null=True)
    Terms = models.TextField(blank=True, null=True)
    Batch_No = models.CharField(max_length=100, default=None, blank=True, null=True)
    Mfd_Date = models.DateField(blank=True, null=True)
    Expiry_Date = models.DateField(blank=True, null=True)


class t_food_licensing_food_handler_t1(models.Model):
    Application_No = models.CharField(max_length=100, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    Nationality = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Permit_No = models.CharField(max_length=100, blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Country_Code = models.IntegerField(default=None, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Training_Request = models.CharField(max_length=250, blank=True, null=True)
    Preferred_Inspection_Place = models.TextField(blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Associated_Food_Establishment = models.TextField(blank=True, null=True)
    Training_Batch_No = models.CharField(max_length=100, blank=True, null=True)
    Training_From_Date = models.DateField(blank=True, null=True)
    Training_To_Date = models.DateField(blank=True, null=True)
    License_Status = models.CharField(max_length=100, blank=True, null=True)
    Assessment_Score = models.IntegerField(blank=True, null=True)
    Minimum_Score = models.IntegerField(blank=True, null=True)
    Trainer = models.CharField(max_length=100, blank=True, null=True)
    FH_License_No = models.CharField(max_length=50, blank=True, null=True)
    Approved_Date = models.DateField(blank=True, null=True)
    FH_License_Validity_Period = models.IntegerField(blank=True, null=True)
    FH_License_Validity = models.DateField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    OIC_Remarks = models.TextField(default=None, blank=True, null=True)
    Inspection_Remarks = models.TextField(default=None, blank=True, null=True)
    Attendance = models.CharField(max_length=5, default=None, blank=True, null=True)
    Training_Venue = models.CharField(max_length=100, default=None, blank=True, null=True)
    Training_Batch = models.CharField(max_length=100, default=None, blank=True, null=True)
    App_Status = models.CharField(max_length=5, default=None, blank=True, null=True)


class t_food_import_permit_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Import_Type = models.CharField(max_length=50, default=None)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Present_Address = models.CharField(max_length=250, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Operation_Type = models.CharField(max_length=100, blank=True, null=True)
    Origin_Country_Food = models.CharField(max_length=250, blank=True, null=True)
    Transit_Country = models.CharField(max_length=5)
    Country_Of_Transit = models.CharField(max_length=100)
    Means_of_Conveyance = models.TextField(blank=True, null=True)
    Place_Of_Entry = models.IntegerField(blank=True, null=True)
    Final_Destination = models.CharField(max_length=250, blank=True, null=True)
    Expected_Arrival_Date = models.DateField(blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Application_Date = models.DateField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    Import_Permit_No = models.CharField(max_length=50, blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Terms = models.TextField(blank=True, null=True)


class t_food_import_permit_t2(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=50)
    Common_Name = models.CharField(max_length=100, blank=True, null=True)
    Product_Category = models.CharField(max_length=100, blank=True, null=True)
    Product_Characteristics = models.CharField(max_length=250, blank=True, null=True)
    Quantity = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=10)
    Exporter_Type = models.CharField(max_length=100, blank=True, null=True)
    Quantity_Balance = models.IntegerField(blank=True, null=True)
    Remarks = models.TextField(blank=True, null=True)


class t_food_import_permit_inspection_t1(models.Model):
    Application_No = models.CharField(max_length=30, primary_key=True)
    Import_Type = models.CharField(max_length=50, default=None)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    CID = models.BigIntegerField(blank=True, null=True)
    Applicant_Name = models.CharField(max_length=250, blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Village_Code = models.CharField(max_length=100, default=None, blank=True, null=True)
    Present_Address = models.CharField(max_length=250, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Email = models.EmailField(blank=True, null=True)
    Operation_Type = models.CharField(max_length=100, blank=True, null=True)
    Origin_Country_Food = models.TextField(blank=True, null=True)
    Transit_Country = models.CharField(max_length=5)
    Country_Of_Transit = models.CharField(max_length=100)
    Means_of_Conveyance = models.TextField(blank=True, null=True)
    Place_Of_Entry = models.IntegerField(blank=True, null=True)
    Final_Destination = models.CharField(max_length=250, blank=True, null=True)
    Expected_Arrival_Date = models.DateField(blank=True, null=True)
    FO_Remarks = models.TextField(blank=True, null=True)
    Application_Date = models.DateField(blank=True, null=True)
    Approve_Date = models.DateField(blank=True, null=True)
    Validity_Period = models.IntegerField(blank=True, null=True)
    Validity = models.DateField(blank=True, null=True)
    Import_Permit_No = models.CharField(max_length=50, blank=True, null=True)
    Proposed_Inspection_Date = models.DateField(blank=True, null=True)
    Actual_Point_Of_Entry = models.IntegerField(blank=True, null=True)
    Inspection_Request_Remarks = models.TextField(blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspection_Type = models.CharField(max_length=250, blank=True, null=True)
    Inspection_Time = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Leader = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Team = models.TextField(blank=True, null=True)
    Clearance_Ref_No = models.CharField(max_length=50, blank=True, null=True)
    Inspection_Remarks = models.TextField(blank=True, null=True)
    Applicant_Id = models.CharField(max_length=100, default=None, blank=True, null=True)
    Terms = models.TextField(blank=True, null=True)


class t_food_import_permit_inspection_t2(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=50)
    Common_Name = models.CharField(max_length=100, blank=True, null=True)
    Product_Category = models.CharField(max_length=100, blank=True, null=True)
    Product_Characteristics = models.CharField(max_length=250, blank=True, null=True)
    Quantity = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=10)
    Exporter_Type = models.CharField(max_length=100, blank=True, null=True)
    Quantity_Released = models.IntegerField(blank=True, null=True)
    Remarks = models.TextField(blank=True, null=True)
    Quantity_Balance = models.IntegerField(blank=True, null=True)
    Quantity_Balance_1 = models.IntegerField(blank=True, null=True)
    Product_Record_Id = models.IntegerField(blank=True, null=True)


class t_food_import_permit_inspection_t3(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Application_No = models.CharField(max_length=50)
    Current_Observation = models.TextField(blank=True, null=True)
    Decision_Conformity = models.TextField(blank=True, null=True)


class t_food_business_registration_licensing_t1(models.Model):
    application_no = models.CharField(max_length=30, primary_key=True)
    application_date = models.DateField()
    applicant_id = models.CharField(max_length=30, default=None, blank=True, null=True)
    business_name = models.CharField(max_length=30, blank=True, null=True)
    cid = models.BigIntegerField(blank=True, null=True)
    name_owner = models.CharField(max_length=30, blank=True, null=True)
    contact_no = models.IntegerField()
    email = models.CharField(max_length=30, blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    name_manager = models.CharField(max_length=100, blank=True, null=True)
    license_criteria = models.CharField(max_length=100, blank=True, null=True)
    product_category = models.TextField(blank=True, null=True)
    product = models.TextField(blank=True, null=True)
    current_status = models.CharField(max_length=250, blank=True, null=True)
    years_in_production = models.IntegerField(default=None, blank=True, null=True)
    volume_last_year = models.CharField(max_length=100, blank=True, null=True)
    volume_unit = models.CharField(max_length=10, default=None, blank=True, null=True)
    project_proposal = models.CharField(max_length=5, blank=True, null=True)
    water_source = models.CharField(max_length=100, blank=True, null=True)
    site_history = models.CharField(max_length=100, blank=True, null=True)
    previous_business = models.CharField(max_length=250, blank=True, null=True)
    process_outsource = models.CharField(max_length=10, blank=True, null=True)
    legal_entity = models.CharField(max_length=100, blank=True, null=True)
    large_corporation = models.CharField(max_length=10, blank=True, null=True)
    large_corporation_relation = models.CharField(max_length=100, blank=True, null=True)
    fbo_license_status = models.CharField(max_length=100, blank=True, null=True)
    fbo_license_no = models.CharField(max_length=100, blank=True, null=True)
    invalid_reason = models.TextField(blank=True, null=True)
    fbo_judicial_proceedings = models.CharField(max_length=100, blank=True, null=True)
    judicial_proceedings_details = models.CharField(max_length=100, blank=True, null=True)
    fbo_regulatory_proceedings = models.CharField(max_length=100, blank=True, null=True)
    regulatory_proceedings_details = models.CharField(max_length=100, blank=True, null=True)
    inspection_type = models.CharField(max_length=100, blank=True, null=True)
    desired_fi_inspection_date = models.DateField(blank=True, null=True)
    desired_fr_inspection_date = models.DateField(blank=True, null=True)
    fb_license_no = models.CharField(max_length=100, blank=True, null=True)  # System Generated FB License No
    fi_inspection_date = models.DateField(blank=True, null=True)
    fi_inspection_leader = models.CharField(max_length=100, blank=True, null=True)
    fi_response = models.TextField(blank=True, null=True)
    fi_recommendation = models.TextField(blank=True, null=True)
    fr_inspection_date = models.DateField(blank=True, null=True)
    fr_inspection_leader = models.CharField(max_length=100, blank=True, null=True)
    fr_response = models.TextField(blank=True, null=True)
    fr_recommendation = models.TextField(blank=True, null=True)
    field_office_id = models.IntegerField(default=None, blank=True, null=True)
    conditional_clearance_no = models.CharField(max_length=100, blank=True, null=True)
    clearance_approve_date = models.DateField(blank=True, null=True)
    clearance_validity_period = models.IntegerField(blank=True, null=True)
    clearance_validity = models.DateField(blank=True, null=True)
    approve_date = models.DateField(blank=True, null=True)
    validity_period = models.IntegerField(blank=True, null=True)
    validity = models.DateField(blank=True, null=True)
    fr_inspection_team = models.CharField(max_length=100, default=None, blank=True, null=True)
    fi_inspection_team = models.CharField(max_length=100, default=None, blank=True, null=True)
    dzongkhag_code = models.IntegerField(default=None, blank=True, null=True)
    gewog_code = models.IntegerField(default=None, blank=True, null=True)
    village_code = models.IntegerField(default=None, blank=True, null=True)
    fo_remarks = models.TextField(blank=True, null=True)
    process_flow_technology = models.TextField(blank=True, null=True)
    quality_assurance_system = models.TextField(blank=True, null=True)
    application_source = models.CharField(max_length=10, blank=True, null=True)


class t_food_business_registration_licensing_t2(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=30)
    bp_outsourced_to = models.CharField(max_length=100)
    contact_no = models.IntegerField(default=None)
    address = models.TextField()
    bafra_license_no = models.CharField(max_length=100, blank=True, null=True)


class t_food_business_registration_licensing_t3(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=30)
    fh_license_no = models.CharField(max_length=30)
    fh_name = models.CharField(max_length=100)


class t_food_business_registration_licensing_t4(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=30)
    meeting_type = models.CharField(max_length=100)
    name = models.CharField(max_length=30)
    designation = models.CharField(max_length=30)
    meeting_date = models.DateField()
    type = models.CharField(max_length=100, default=None, blank=True, null=True)


class t_food_business_registration_licensing_t5(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=30)
    inspection_type = models.CharField(max_length=100)
    requirement = models.TextField()
    observation = models.TextField(default=None, blank=True, null=True)
    clause_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    concern = models.CharField(max_length=10, default=None, blank=True, null=True)
    date = models.DateField(default=None, blank=True, null=True)
    fbo_response = models.TextField(default=None, blank=True, null=True)
    nc = models.CharField(max_length=10, default=None, blank=True, null=True)
    nc_category = models.CharField(max_length=10, default=None, blank=True, null=True)


class t_food_business_registration_licensing_t6(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=30)
    meeting_type = models.CharField(max_length=100)
    name = models.CharField(max_length=30)
    designation = models.CharField(max_length=30)


class t_food_business_registration_licensing_t7(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=30)
    name = models.CharField(max_length=100)
    source_country = models.CharField(max_length=30)


class t_food_business_registration_licensing_t8(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=30)
    name = models.CharField(max_length=100)
    source_country = models.CharField(max_length=30)
