from django.db import models


# Create your models here.

class t_common_complaint_t1(models.Model):
    Application_No = models.CharField(max_length=20, primary_key=True)
    Application_Date = models.DateField(blank=True, null=True)
    Applicant_Id = models.CharField(blank=True, null=True, max_length=100)
    CID = models.BigIntegerField()
    Name = models.CharField(blank=True, null=True, max_length=100)
    Dzongkhag_Code = models.IntegerField(default=None, blank=True, null=True)
    Gewog_Code = models.IntegerField(default=None, blank=True, null=True)
    Village_Code = models.IntegerField(default=None, blank=True, null=True)
    Contact_No = models.IntegerField()
    Email = models.EmailField()
    Address = models.CharField(blank=True, null=True, max_length=250)
    Complaint_Type = models.CharField(blank=True, null=True, max_length=100)
    Complaint_Description = models.TextField(blank=True, null=True)
    Acknowledge = models.CharField(blank=True, null=True, max_length=1)
    Assign_To = models.CharField(blank=True, null=True, max_length=100)
    Assign_Date = models.DateField(blank=True, null=True)
    Assign_Remarks = models.TextField(blank=True, null=True)
    Investigation_Date = models.DateField(blank=True, null=True)
    Investigation_By = models.TextField(blank=True, null=True)
    Investigation_Report = models.TextField(blank=True, null=True)
    Report_Submit_Date = models.DateField(blank=True, null=True)
    Closure_Date = models.DateField(blank=True, null=True)
    Closure_Remarks = models.TextField(blank=True, null=True)
    Application_Status = models.CharField(blank=True, null=True, max_length=50)


class t_Inspection_monitoring_t1(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Reference_No = models.CharField(max_length=30, blank=True, null=True)
    Inspection_Type = models.CharField(max_length=100, blank=True, null=True)
    FBO_Name = models.CharField(max_length=100, blank=True, null=True)
    License_No = models.CharField(max_length=100, blank=True, null=True)
    Address = models.CharField(max_length=250, blank=True, null=True)
    Email = models.CharField(max_length=100, blank=True, null=True)
    Contact_No = models.IntegerField(blank=True, null=True)
    Dzongkhag_Code = models.CharField(max_length=10, blank=True, null=True)
    Gewog_Code = models.CharField(max_length=10, blank=True, null=True)
    Village_Code = models.CharField(max_length=10, blank=True, null=True)
    Inspected_By = models.CharField(max_length=10, blank=True, null=True)
    Inspector_Name = models.CharField(max_length=100, blank=True, null=True)
    Designation = models.CharField(max_length=100, blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspection_Reason = models.CharField(max_length=20, blank=True, null=True)
    Farm_Owner_Name = models.CharField(max_length=100, blank=True, null=True)
    Farm_Ownership = models.CharField(max_length=20, blank=True, null=True)
    Geo_Coordinate_X = models.IntegerField(blank=True, null=True)
    Geo_Coordinate_Y = models.IntegerField(blank=True, null=True)
    Livestock_Reared = models.CharField(max_length=100, blank=True, null=True)
    Farm_Type = models.CharField(max_length=20, blank=True, null=True)
    Farm_Size = models.IntegerField(blank=True, null=True)
    Establish_Year = models.IntegerField(blank=True, null=True)
    Sign_Board = models.IntegerField(blank=True, null=True)
    Perimeter_Fence = models.IntegerField(blank=True, null=True)
    Foot_Dip = models.IntegerField(blank=True, null=True)
    Tyre_Dip = models.IntegerField(blank=True, null=True)
    Waste_Bin = models.IntegerField(blank=True, null=True)
    Wash_Station = models.IntegerField(blank=True, null=True)
    Changing_Rooms = models.IntegerField(blank=True, null=True)
    Farm_Gears = models.IntegerField(blank=True, null=True)
    Farm_Distance = models.IntegerField(blank=True, null=True)
    Shed_Surroundings = models.IntegerField(blank=True, null=True)
    Good_Drainage = models.IntegerField(blank=True, null=True)
    Shed_Food_Dip = models.IntegerField(blank=True, null=True)
    Shed_Wash_Station = models.IntegerField(blank=True, null=True)
    Separate_Shed_Isolation = models.IntegerField(blank=True, null=True)
    Separate_Shed_Quarantine = models.IntegerField(blank=True, null=True)
    Store_Rood = models.IntegerField(blank=True, null=True)
    Shed_Cleanliness = models.IntegerField(blank=True, null=True)
    Shed_Disinfected = models.IntegerField(blank=True, null=True)
    Workers_Farm_Gear = models.IntegerField(blank=True, null=True)
    Animal_Isolation = models.IntegerField(blank=True, null=True)
    Days_Isolated = models.IntegerField(blank=True, null=True)
    Vaccination_Schedule = models.IntegerField(blank=True, null=True)
    Deworming_Interval = models.IntegerField(blank=True, null=True)
    Animal_Check = models.IntegerField(blank=True, null=True)
    Isolation_Treatment = models.IntegerField(blank=True, null=True)
    Sick_Report = models.IntegerField(blank=True, null=True)
    Mortality_Report = models.IntegerField(blank=True, null=True)
    Feed_Water_Through = models.IntegerField(blank=True, null=True)
    Feed_Kitchen_Scraps = models.IntegerField(blank=True, null=True)
    Farm_Water_Source = models.IntegerField(blank=True, null=True)
    Farm_Waste_Dispose = models.IntegerField(blank=True, null=True)
    Dispose_Method = models.IntegerField(blank=True, null=True)
    Visitors_Briefing = models.IntegerField(blank=True, null=True)
    Refrain_Visitors = models.IntegerField(blank=True, null=True)
    Separate_Store_Room = models.IntegerField(blank=True, null=True)
    Feed_Store_Cleanliness = models.IntegerField(blank=True, null=True)
    Equipment_Cleanliness = models.IntegerField(blank=True, null=True)
    Equipment_Share = models.IntegerField(blank=True, null=True)
    Treatment_Record = models.IntegerField(blank=True, null=True)
    Vaccination_Record = models.IntegerField(blank=True, null=True)
    Deworming_Record = models.IntegerField(blank=True, null=True)
    Morbidity_Record = models.IntegerField(blank=True, null=True)
    Mortality_Record = models.IntegerField(blank=True, null=True)
    Medicine_Record = models.IntegerField(blank=True, null=True)
    Feed_Record = models.IntegerField(blank=True, null=True)
    Animal_Stock_Record = models.IntegerField(blank=True, null=True)
    Production_Record = models.IntegerField(blank=True, null=True)
    Observation = models.TextField(blank=True, null=True)
    Team_Leader = models.CharField(max_length=20, blank=True, null=True)
    Assigned_Date = models.DateField(blank=True, null=True)
    Application_Status = models.CharField(max_length=5, blank=True, null=True)
    Food_Certificate_No = models.CharField(max_length=20, blank=True, null=True)


class t_Inspection_monitoring_t2(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Reference_No = models.CharField(max_length=30, blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspector_Name = models.CharField(max_length=30, blank=True, null=True)
    Observation = models.CharField(max_length=30, blank=True, null=True)
    Correction_Proposed = models.CharField(max_length=30, blank=True, null=True)
    Date_Line_Correction = models.DateField(blank=True, null=True)
    Correction_Taken = models.CharField(max_length=30, blank=True, null=True)
    Fine_Imposed = models.IntegerField(blank=True, null=True)
    Revenue_Receipt = models.CharField(max_length=30, blank=True, null=True)
    Receipt_Date = models.DateField(blank=True, null=True)


class t_Inspection_monitoring_t3(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Reference_No = models.CharField(max_length=30, blank=True, null=True)
    Inspection_Date = models.DateField(blank=True, null=True)
    Inspector_Name = models.CharField(max_length=30, blank=True, null=True)
    Items_Seized = models.CharField(max_length=30, blank=True, null=True)
    Qty_Seized = models.IntegerField(blank=True, null=True)
    Unit = models.CharField(max_length=10, blank=True, null=True)
    Reason = models.CharField(max_length=250, blank=True, null=True)
    Fine_Imposed = models.IntegerField(blank=True, null=True)
    Revenue_Receipt = models.CharField(max_length=30, blank=True, null=True)
    Receipt_Date = models.DateField(blank=True, null=True)


class t_Inspection_monitoring_t4(models.Model):
    Record_Id = models.AutoField(primary_key=True)
    Reference_No = models.CharField(max_length=30, blank=True, null=True)
    Collection_Type = models.CharField(max_length=30, blank=True, null=True)
    Collection_Date = models.DateField(blank=True, null=True)
    Submission_Date = models.DateField(blank=True, null=True)
    HS_Code_Imp = models.CharField(max_length=30, blank=True, null=True)
    HS_Code_Local = models.CharField(max_length=30, blank=True, null=True)
    Sample_Type = models.CharField(max_length=100, blank=True, null=True)
    Qty = models.IntegerField(blank=True, null=True)
    Batch_No_Date = models.CharField(max_length=100, blank=True, null=True)
    Test_Requested = models.CharField(max_length=100, blank=True, null=True)
    Test_Report = models.CharField(max_length=100, blank=True, null=True)
