from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from common_service import views

urlpatterns = [
    # Complaint service
    path('save_complaint', views.save_complaint, name='save_complaint'),
    path('submit_complaint', views.submit_complaint, name='submit_complaint'),
    path('load_gewog', views.load_gewog, name='load_gewog'),
    path('load_village', views.load_village, name='load_village'),
    path('co_complaint_list', views.co_complaint_list, name='co_complaint_list'),
    path('investigation_complaint_list', views.investigation_complaint_list, name='investigation_complaint_list'),
    path("investigation_complaint_details", views.investigation_complaint_details,
         name="investigation_complaint_details"),
    path('co_complaint_details', views.co_complaint_details, name='co_complaint_details'),
    path('apply_complaint_form', views.apply_complaint_form, name='apply_complaint_form'),
    path('complaint_details', views.complaint_details, name='complaint_details'),
    path('acknowledge_complaint', views.acknowledge_complaint, name='acknowledge_complaint'),
    path('forward_complaint_by_co', views.forward_complaint_by_co, name='forward_complaint_by_co'),
    path('forward_complaint_to_co', views.forward_complaint_to_co, name='forward_complaint_to_co'),
    path('investigation_report_list', views.investigation_report_list, name='investigation_report_list'),
    path('investigation_report_details', views.investigation_report_details, name='investigation_report_details'),
    path('close_complaint', views.close_complaint, name='close_complaint'),
    path('complaint_closed_list', views.complaint_closed_list, name='complaint_closed_list'),
    path('complaint_closed_details', views.complaint_closed_details, name='complaint_closed_details'),
    path('load_complaint_attachment_details', views.load_complaint_attachment_details,
         name='load_complaint_attachment_details'),
    path('save_complaint_file', views.save_complaint_file, name='save_complaint_file'),
    path('add_complaint_file_name', views.add_complaint_file_name, name='add_complaint_file_name'),
    path('delete_complaint_file', views.delete_complaint_file, name='delete_complaint_file'),
    path('load_investigation_attachment_details', views.load_investigation_attachment_details,
         name='load_investigation_attachment_details'),
    path('save_investigation_file', views.save_investigation_file, name='save_investigation_file'),
    path('add_investigation_file_name', views.add_investigation_file_name, name='add_investigation_file_name'),
    path('delete_investigation_file', views.delete_investigation_file, name='delete_investigation_file'),

# Establishment Inspection and Monitoring
    path('establishment_inspection_form', views.establishment_inspection_form,
         name='establishment_inspection_form'),
    path('save_monitoring_form', views.save_monitoring_form, name='save_monitoring_form'),
    path('save_sample_details', views.save_sample_details, name='save_sample_details'),
    path('save_item_details', views.save_item_details, name='save_item_details'),
    path('save_owner_manager_details', views.save_owner_manager_details, name='save_owner_manager_details'),
    path('inspection_file', views.inspection_file, name='inspection_file'),
    path('inspection_file_name', views.inspection_file_name, name='inspection_file_name'),
    path('submit_establishment_inspection_form', views.submit_establishment_inspection_form, name='submit_establishment_inspection_form'),
    path('draft_application_list', views.draft_application_list, name='draft_application_list'),
    path('view_draft_details', views.view_draft_details, name='view_draft_details'),
    path('update_inspection_details', views.update_inspection_details, name='update_inspection_details'),
    path('submit_draft_inspection_details', views.submit_draft_inspection_details,
         name='submit_draft_inspection_details'),
    path('load_establishment_attachment_details', views.load_establishment_attachment_details,
         name='load_establishment_attachment_details'),
    path('delete_establishment_file', views.delete_establishment_file, name='delete_establishment_file'),
    path('delete_nc_details', views.delete_nc_details, name='delete_nc_details'),
    path('delete_seized_details', views.delete_seized_details, name='delete_seized_details'),
    path('delete_collection_details', views.delete_collection_details, name='delete_collection_details'),
    path('view_establishment_inspection_list', views.view_establishment_inspection_list,
         name='view_establishment_inspection_list'),
    path('view_establishment_inspection_details', views.view_establishment_inspection_details,
         name='view_establishment_inspection_details'),

# Commodity Inspection and Monitoring
    path('commodity_inspection_form', views.commodity_inspection_form,
         name='commodity_inspection_form'),
    path('save_inspection_report_application', views.save_inspection_report_application,
         name='save_inspection_report_application'),
    path('save_commodity_details', views.save_commodity_details, name='save_commodity_details'),
    path('submit_commodity_inspection_form', views.submit_commodity_inspection_form, name='submit_commodity_inspection_form'),
    path('load_commodity_application_details', views.load_commodity_application_details,
         name='load_commodity_application_details'),
    path('draft_inspection_application_details', views.draft_inspection_application_details,
         name='draft_inspection_application_details'),
    path('load_commodity_attachment_details', views.load_commodity_attachment_details,
         name='load_commodity_attachment_details'),
    path('add_commodity_file', views.add_commodity_file, name='add_commodity_file'),
    path('add_commodity_file_name', views.add_commodity_file_name, name='add_commodity_file_name'),
    path('delete_commodity_file', views.delete_commodity_file, name='delete_commodity_file'),
    path('delete_commodity_details', views.delete_commodity_details, name='delete_commodity_details'),
    path('draft_commodity_inspection_list', views.draft_commodity_inspection_list,
         name='draft_commodity_inspection_list'),
    path('view_draft_commodity_inspection_details', views.view_draft_commodity_inspection_details,
         name='view_draft_commodity_inspection_details'),
    path('update_inspection_report_application', views.update_inspection_report_application,
         name='update_inspection_report_application'),
    path('update_commodity_details', views.update_commodity_details, name='update_commodity_details'),
    path('view_commodity_inspection_list', views.view_commodity_inspection_list,
         name='view_commodity_inspection_list'),
    path('view_commodity_inspection_details', views.view_commodity_inspection_details,
         name='view_commodity_inspection_details'),
    path('view_FHC_inspection_details', views.view_FHC_inspection_details,
         name='view_FHC_inspection_details')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
