# Generated by Django 3.1.7 on 2021-05-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
