# Generated by Django 3.1.5 on 2021-11-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_food_t3',
            name='Service_Code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
