# Generated by Django 3.1.5 on 2022-06-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20220623_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_food_t5',
            name='Non_Conformity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
