# Generated by Django 3.1.5 on 2021-08-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20210827_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Accredited_Non_Accredited',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
