# Generated by Django 3.1.5 on 2021-05-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_auto_20210512_1813'),
        ('certification', '0003_auto_20210514_1426'),
    ]

    operations = [
    ]
