# Generated by Django 3.1.5 on 2021-08-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0003_t_certification_gap_t1_accredited_non_accredited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Accredited_Non_Accredited',
            new_name='Certificate_Type',
        ),
        migrations.RemoveField(
            model_name='t_certification_food_t5',
            name='Corrective_Action_Date',
        ),
        migrations.RemoveField(
            model_name='t_certification_food_t5',
            name='Corrective_Action_Taken_Auditee',
        ),
        migrations.RemoveField(
            model_name='t_certification_organic_t11',
            name='Corrective_Action_Date',
        ),
        migrations.RemoveField(
            model_name='t_certification_organic_t11',
            name='Corrective_Action_Taken_Auditee',
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Certificate_Type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Corrective_Action_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Corrective_Action_Taken_Auditee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Certificate_Type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Corrective_Action_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Corrective_Action_Taken_Auditee',
            field=models.TextField(blank=True, null=True),
        ),
    ]
