# Generated by Django 3.1.5 on 2021-05-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_merge_20210516_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Farm_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Farm_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
