# Generated by Django 3.1.5 on 2021-08-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_auto_20210827_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='License_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Manager_In_Charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Technical_In_Charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='License_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Manager_In_Charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Technical_In_Charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
