# Generated by Django 3.1.5 on 2021-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0005_auto_20210828_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_organic_t11',
            name='Non_Conformity_Category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t11',
            name='Non_Conformity_Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
