# Generated by Django 3.1.5 on 2021-05-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0006_auto_20210516_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='C_Export_From_Date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='C_Export_To_Date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='C_Export_Value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='P_Export_From_Date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='P_Export_To_Date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='P_Export_Value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='C_Export',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='P_Export',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
