# Generated by Django 3.1.5 on 2021-05-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_auto_20210516_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Terms_Abide',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Terms_Agreement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Terms_Bafra_Certification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Terms_Change_Willingness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
