# Generated by Django 3.1.5 on 2021-08-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0007_auto_20210828_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Factory_Contact_No',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
