# Generated by Django 3.1.5 on 2021-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0008_auto_20210516_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Terms_Abide',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Terms_Agreement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Terms_Bafra_Certification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Terms_Change_Willingness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Terms_Abide',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Terms_Agreement',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Terms_Bafra_Certification',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Terms_Change_Willingness',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
