# Generated by Django 3.1.5 on 2021-08-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0008_auto_20210830_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_gap_t5',
            name='C_Balance_Stock_Unit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
