# Generated by Django 3.1.5 on 2021-05-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0009_auto_20210517_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Audit_Team_Acceptance',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Audit_Team_Acceptance',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Audit_Team_Acceptance',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
