# Generated by Django 3.1.7 on 2021-09-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0009_t_certification_gap_t5_c_balance_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_food_t2',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t3',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t4',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_food_t5',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t2',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t3',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t4',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t5',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t6',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t7',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t8',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t10',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t11',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t2',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t3',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t4',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t5',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t6',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t7',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t8',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t9',
            name='Application_No',
            field=models.CharField(max_length=30),
        ),
    ]
