# Generated by Django 3.1.7 on 2021-09-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0010_auto_20210908_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='License_Number',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Others_Standards',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
