# Generated by Django 3.1.5 on 2021-05-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0011_auto_20210525_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_certification_gap_t5',
            name='Processing_Type',
        ),
    ]
