# Generated by Django 3.1.5 on 2021-05-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0012_remove_t_certification_gap_t5_processing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_food_t3',
            name='Role',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t3',
            name='Role',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t3',
            name='Role',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
