# Generated by Django 3.1.5 on 2021-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0013_auto_20211006_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_gap_t5',
            name='C_Sold_Unit',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
