# Generated by Django 3.1.5 on 2021-05-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0013_auto_20210526_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Equipment',
            new_name='Audit_Findings_Equipment_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Group_Requirement',
            new_name='Audit_Findings_Equipment_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Harvesting',
            new_name='Audit_Findings_Group_Requirement_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Manufacturing_Production',
            new_name='Audit_Findings_Group_Requirement_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Others',
            new_name='Audit_Findings_Harvesting_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Packing_Marking',
            new_name='Audit_Findings_Harvesting_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Product_Quality',
            new_name='Audit_Findings_Manufacturing_Production_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Sampling_Testing',
            new_name='Audit_Findings_Manufacturing_Production_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Site_History',
            new_name='Audit_Findings_Others_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Storage_Transport',
            new_name='Audit_Findings_Others_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Traceability',
            new_name='Audit_Findings_Packing_Marking_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Water_Source',
            new_name='Audit_Findings_Packing_Marking_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_food_t1',
            old_name='Audit_Findings_Worker_Health',
            new_name='Audit_Findings_Product_Quality_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Equipment',
            new_name='Audit_Findings_Equipment_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Group_Requirement',
            new_name='Audit_Findings_Equipment_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Harvesting',
            new_name='Audit_Findings_Group_Requirement_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Manufacturing_Production',
            new_name='Audit_Findings_Group_Requirement_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Others',
            new_name='Audit_Findings_Harvesting_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Packing_Marking',
            new_name='Audit_Findings_Harvesting_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Product_Quality',
            new_name='Audit_Findings_Manufacturing_Production_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Sampling_Testing',
            new_name='Audit_Findings_Manufacturing_Production_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Site_History',
            new_name='Audit_Findings_Others_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Storage_Transport',
            new_name='Audit_Findings_Others_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Traceability',
            new_name='Audit_Findings_Packing_Marking_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Water_Source',
            new_name='Audit_Findings_Packing_Marking_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_gap_t1',
            old_name='Audit_Findings_Worker_Health',
            new_name='Audit_Findings_Product_Quality_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Equipment',
            new_name='Audit_Findings_Equipment_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Group_Requirement',
            new_name='Audit_Findings_Equipment_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Harvesting',
            new_name='Audit_Findings_Group_Requirement_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Manufacturing_Production',
            new_name='Audit_Findings_Group_Requirement_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Others',
            new_name='Audit_Findings_Harvesting_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Packing_Marking',
            new_name='Audit_Findings_Harvesting_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Product_Quality',
            new_name='Audit_Findings_Manufacturing_Production_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Sampling_Testing',
            new_name='Audit_Findings_Manufacturing_Production_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Site_History',
            new_name='Audit_Findings_Others_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Storage_Transport',
            new_name='Audit_Findings_Others_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Traceability',
            new_name='Audit_Findings_Packing_Marking_OE',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Water_Source',
            new_name='Audit_Findings_Packing_Marking_Observations',
        ),
        migrations.RenameField(
            model_name='t_certification_organic_t1',
            old_name='Audit_Findings_Worker_Health',
            new_name='Audit_Findings_Product_Quality_OE',
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Product_Quality_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Sampling_Testing_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Sampling_Testing_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Site_History_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Site_History_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Storage_Transport_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Storage_Transport_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Traceability_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Traceability_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Water_Source_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Water_Source_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Worker_Health_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='Audit_Findings_Worker_Health_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Product_Quality_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Sampling_Testing_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Sampling_Testing_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Site_History_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Site_History_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Storage_Transport_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Storage_Transport_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Traceability_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Traceability_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Water_Source_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Water_Source_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Worker_Health_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Audit_Findings_Worker_Health_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Product_Quality_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Sampling_Testing_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Sampling_Testing_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Site_History_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Site_History_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Storage_Transport_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Storage_Transport_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Traceability_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Traceability_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Water_Source_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Water_Source_Observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Worker_Health_OE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_organic_t1',
            name='Audit_Findings_Worker_Health_Observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
