# Generated by Django 3.1.5 on 2021-05-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0014_auto_20210526_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_gap_t8',
            name='Non_Conformity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
