# Generated by Django 3.1.5 on 2021-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0016_auto_20210526_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Audit_Plan_Acceptance',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
