# Generated by Django 3.1.5 on 2021-05-26 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0017_auto_20210526_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_certification_food_t1',
            name='C_Export_From_Date',
        ),
        migrations.RemoveField(
            model_name='t_certification_food_t1',
            name='C_Export_To_Date',
        ),
        migrations.RemoveField(
            model_name='t_certification_food_t1',
            name='P_Export_From_Date',
        ),
        migrations.RemoveField(
            model_name='t_certification_food_t1',
            name='P_Export_To_Date',
        ),
    ]
