# Generated by Django 3.1.5 on 2021-05-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0018_auto_20210526_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='C_Export_From_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='C_Export_To_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='P_Export_From_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_food_t1',
            name='P_Export_To_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
