# Generated by Django 3.1.5 on 2021-06-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0019_auto_20210526_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Audit_Team_Leader',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
