# Generated by Django 3.1.5 on 2021-06-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0020_auto_20210601_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Audit_Team_Leader',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Audit_Team_Leader',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
