# Generated by Django 3.1.5 on 2021-06-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0022_auto_20210602_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_certification_food_t1',
            name='Audit_Team_Acceptance',
            field=models.CharField(blank=True, default='R', max_length=1, null=True),
        ),
    ]
