# Generated by Django 3.1.5 on 2021-07-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0023_auto_20210603_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='License_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Manager_In_Charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_certification_gap_t1',
            name='Technical_In_Charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_gap_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_certification_organic_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
