# Generated by Django 3.1.5 on 2021-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_plant_movement_permit_t1',
            fields=[
                ('Application_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Permit_Type', models.CharField(default=None, max_length=1)),
                ('License_No', models.CharField(max_length=100)),
                ('Nursery_Name', models.CharField(max_length=100)),
                ('CID', models.BigIntegerField()),
                ('Applicant_Name', models.CharField(max_length=250)),
                ('Contact_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Dzongkhag_Code', models.IntegerField()),
                ('Gewog_Code', models.IntegerField()),
                ('Village_Code', models.IntegerField()),
                ('Location_Code', models.IntegerField()),
                ('From_Dzongkhag_Code', models.IntegerField()),
                ('To_Dzongkhag_Code', models.IntegerField()),
                ('Authorized_Route', models.CharField(max_length=100)),
                ('Source_Of_Product', models.CharField(max_length=100)),
                ('Movement_Purpose', models.CharField(max_length=100)),
                ('Conveyance_Means', models.CharField(max_length=20)),
                ('Name_And_Description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Vehicle_No', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Movement_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Leader', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Inspection_Team', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Application_Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('Movement_Permit_No', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_movement_permit_t2',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Commodity', models.CharField(max_length=100)),
                ('Qty', models.IntegerField()),
                ('Remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_movement_permit_t3',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Current_Observation', models.TextField()),
                ('Decision_Conformity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='t_workflow_details',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Applicant_Id', models.CharField(max_length=20)),
                ('Assigned_To', models.CharField(max_length=100)),
                ('Field_Office_Id', models.IntegerField()),
                ('Section', models.CharField(max_length=20)),
                ('Action_Date', models.DateField()),
                ('Application_Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_workflow_details_audit',
            fields=[
                ('Audit_Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Workflow_Record_Id', models.IntegerField()),
                ('Application_No', models.CharField(max_length=20)),
                ('Applicant_Id', models.CharField(max_length=20)),
                ('Assigned_To', models.CharField(max_length=100)),
                ('Field_Office_Id', models.IntegerField()),
                ('Section', models.CharField(max_length=20)),
                ('Action_Date', models.DateField()),
                ('Application_Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
            ],
        ),
    ]
