# Generated by Django 3.1.5 on 2021-08-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_import_permit_t2',
            name='Quantity_Rejected',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
