# Generated by Django 3.1.5 on 2021-10-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Dzongkhag',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Gewog',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Location_Code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Village',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
