# Generated by Django 3.1.5 on 2022-04-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_payment_details_master',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_head_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('account_head_code', models.BigIntegerField(blank=True, default=None, null=True)),
                ('service_fee', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='account_head_code',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
