# Generated by Django 3.1.5 on 2021-08-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_seed_certification_t2',
            name='Unit_Certified',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
