# Generated by Django 3.1.5 on 2021-12-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_plant_clearence_nursery_seed_grower_t3',
            fields=[
                ('Record_Id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Application_No', models.CharField(default=None, max_length=30)),
                ('Observation', models.TextField(blank=True, null=True)),
                ('Action', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Current_Observation',
        ),
        migrations.RemoveField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Decision_Conformity',
        ),
    ]
