# Generated by Django 3.1.5 on 2021-04-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_seed_certification_t1',
            name='Application_No',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='t_plant_seed_certification_t1',
            name='CID',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_seed_certification_t1',
            name='Contact_No',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
