# Generated by Django 3.1.5 on 2021-02-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_file_attachment',
            fields=[
                ('File_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Applicant_Id', models.CharField(max_length=20)),
                ('Role_Id', models.IntegerField(blank=True, null=True)),
                ('File_Name', models.CharField(max_length=100)),
                ('File_Path', models.CharField(max_length=255)),
            ],
        ),
    ]
