# Generated by Django 3.1.5 on 2021-08-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_t_plant_import_permit_t2_quantity_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Common_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
