# Generated by Django 3.1.5 on 2021-03-03 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_file_attachment',
            name='File_Name',
        ),
        migrations.RemoveField(
            model_name='t_file_attachment',
            name='File_Path',
        ),
        migrations.AddField(
            model_name='t_file_attachment',
            name='Attachment',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Assigned_To',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
