# Generated by Django 3.1.5 on 2021-06-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20210531_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Application_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
