# Generated by Django 3.1.5 on 2021-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20211211_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_payment_details',
            name='Permit_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
