# Generated by Django 3.1.5 on 2021-10-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_auto_20211021_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Resubmit_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
