# Generated by Django 3.1.5 on 2021-10-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_t_plant_seed_certification_t1_resubmit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_payment_details',
            name='Validity',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
