# Generated by Django 3.1.5 on 2022-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_auto_20220518_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_payment_details_master',
            old_name='accountHeadId',
            new_name='account_head_code',
        ),
        migrations.RenameField(
            model_name='t_payment_details_master',
            old_name='serviceFee',
            new_name='service_fee',
        ),
        migrations.AddField(
            model_name='t_payment_details_master',
            name='service_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
