# Generated by Django 3.1.5 on 2021-03-04 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
        ('plant', '0003_auto_20210303_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_plant_import_permit_t3',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Current_Observation', models.TextField()),
                ('Decision_Conformity', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Application_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Attachment',
            field=models.FileField(upload_to='attachments/'),
        ),
        migrations.CreateModel(
            name='t_plant_import_permit_t2',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Import_Category', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('Unit', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Quantity_Released', models.CharField(max_length=10)),
                ('Remarks', models.CharField(max_length=250)),
                ('Crop_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.t_plant_crop_master')),
                ('Pesticide_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.t_plant_pesticide_master')),
                ('Variety_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.t_plant_crop_variety_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_import_permit_t1',
            fields=[
                ('Application_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Import_Type', models.CharField(default=None, max_length=1)),
                ('License_No', models.CharField(max_length=100)),
                ('Business_Name', models.CharField(max_length=100)),
                ('CID', models.BigIntegerField()),
                ('Applicant_Name', models.CharField(max_length=250)),
                ('Present_Address', models.CharField(max_length=250)),
                ('Contact_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Name_And_Address_Supplier', models.TextField()),
                ('Means_of_Conveyance', models.TextField()),
                ('Purpose', models.TextField()),
                ('Final_Destination', models.CharField(max_length=250)),
                ('Import_Inspection_Submit_Date', models.DateField(blank=True, null=True)),
                ('Proposed_Inspection_Date', models.DateField(blank=True, null=True)),
                ('Actual_Point_Of_Entry', models.IntegerField(blank=True, null=True)),
                ('Inspection_Request_Remarks', models.TextField(blank=True, null=True)),
                ('Import_Permit_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Inspection_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Type', models.CharField(blank=True, max_length=250, null=True)),
                ('Inspection_Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Inspection_Leader', models.CharField(blank=True, max_length=100, null=True)),
                ('Inspection_Team', models.TextField(blank=True, null=True)),
                ('Clearance_Ref_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Place_Of_Entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.t_location_field_office_mapping')),
            ],
        ),
    ]
