# Generated by Django 3.1.5 on 2021-08-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_t_plant_export_certificate_plant_plant_products_t1_common_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_plant_import_permit_inspection_t1',
            fields=[
                ('Application_No', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Import_Type', models.CharField(default=None, max_length=1)),
                ('Application_Type', models.CharField(default=None, max_length=10)),
                ('Nationality_Type', models.CharField(default=None, max_length=10)),
                ('License_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Business_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('CID', models.BigIntegerField(blank=True, null=True)),
                ('Applicant_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Present_Address', models.CharField(blank=True, max_length=250, null=True)),
                ('Contact_No', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Name_And_Address_Supplier', models.TextField(blank=True, null=True)),
                ('Means_of_Conveyance', models.TextField(blank=True, null=True)),
                ('Place_Of_Entry', models.IntegerField(blank=True, null=True)),
                ('Purpose', models.TextField(blank=True, null=True)),
                ('Final_Destination', models.CharField(blank=True, max_length=250, null=True)),
                ('Import_Inspection_Submit_Date', models.DateField(blank=True, null=True)),
                ('Proposed_Inspection_Date', models.DateField(blank=True, null=True)),
                ('Actual_Point_Of_Entry', models.IntegerField(blank=True, null=True)),
                ('Inspection_Request_Remarks', models.TextField(blank=True, null=True)),
                ('Import_Permit_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Inspection_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Type', models.CharField(blank=True, max_length=250, null=True)),
                ('Inspection_Time', models.CharField(blank=True, max_length=100, null=True)),
                ('Inspection_Leader', models.CharField(blank=True, max_length=100, null=True)),
                ('Inspection_Team', models.TextField(blank=True, null=True)),
                ('Clearance_Ref_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Expected_Arrival_Date', models.DateField(blank=True, null=True)),
                ('FO_Remarks', models.TextField(blank=True, null=True)),
                ('Inspection_Remarks', models.TextField(blank=True, null=True)),
                ('Country_Of_Origin', models.TextField(blank=True, null=True)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(max_length=100)),
                ('Approved_Date', models.DateField(blank=True, default=None, null=True)),
                ('Validity_Period', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Validity', models.DateField(blank=True, default=None, null=True)),
                ('passport_number', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Nationality', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('dzongkhag', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gewog', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('village', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_import_permit_inspection_t2',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Import_Category', models.CharField(max_length=20)),
                ('Crop_Id', models.IntegerField(blank=True, null=True)),
                ('Pesticide_Id', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Variety_Id', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('Quantity_Released', models.CharField(blank=True, max_length=10, null=True)),
                ('Quantity_Rejected', models.CharField(blank=True, max_length=10, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Quantity_Balance', models.IntegerField(blank=True, null=True)),
                ('Product_Record_Id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='t_plant_import_permit_t3',
            new_name='t_plant_import_permit_inspection_t3',
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t2',
            name='Quantity_Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
