# Generated by Django 3.1.5 on 2021-06-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_auto_20210603_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Application_Type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Nationality',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
