# Generated by Django 3.1.5 on 2022-01-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0003_t_payment_details_permit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_inspection_t1',
            name='Nationality_Type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
