# Generated by Django 3.1.5 on 2021-10-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20211023_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='License_No',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='Nursery_Name',
            field=models.CharField(blank=True, default='NA', max_length=100, null=True),
        ),
    ]
