# Generated by Django 3.1.5 on 2021-09-09 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20210830_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            old_name='contactNo',
            new_name='Contact_No',
        ),
        migrations.RenameField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            old_name='location_code',
            new_name='Location_Code',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_inspection_t1',
            old_name='dzongkhag',
            new_name='Dzongkhag',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_inspection_t1',
            old_name='gewog',
            new_name='Gewog',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_inspection_t1',
            old_name='passport_number',
            new_name='Passport_Number',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_inspection_t1',
            old_name='village',
            new_name='Village',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_t1',
            old_name='dzongkhag',
            new_name='Dzongkhag',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_t1',
            old_name='gewog',
            new_name='Gewog',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_t1',
            old_name='passport_number',
            new_name='Passport_Number',
        ),
        migrations.RenameField(
            model_name='t_plant_import_permit_t1',
            old_name='village',
            new_name='Village',
        ),
    ]
