# Generated by Django 3.1.5 on 2021-04-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20210406_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t2',
            name='Crop_Id',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t2',
            name='Variety_Id',
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t2',
            name='Crop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t2',
            name='Variety',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
