# Generated by Django 3.1.5 on 2021-03-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20210304_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Attachment',
            field=models.FileField(upload_to='plant/'),
        ),
    ]
