# Generated by Django 3.1.5 on 2022-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20220610_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_plant_export_certificate_plant_plant_products_t2',
            fields=[
                ('Record_Id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('Application_No', models.CharField(default=None, max_length=30)),
                ('Botanical_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Common_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('Unit', models.CharField(blank=True, max_length=10, null=True)),
                ('Gross_Weight', models.CharField(blank=True, max_length=100, null=True)),
                ('Net_Weight', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Botanical_Name',
        ),
        migrations.RemoveField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Common_Name',
        ),
        migrations.RemoveField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Description',
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_inspection_t2',
            name='Quantity_Rejected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_inspection_t2',
            name='Quantity_Released',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Quantity_Rejected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Quantity_Released',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
