# Generated by Django 3.1.5 on 2021-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0004_auto_20210625_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Dzongkhag_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Gewog_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Nationality_Type',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Village_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='passport_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
