# Generated by Django 3.1.5 on 2022-06-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20220625_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workflow_details',
            name='application_source',
            field=models.CharField(blank=True, default='BBFSS', max_length=100, null=True),
        ),
    ]
