# Generated by Django 3.1.5 on 2021-09-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20210909_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Nationality_Type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
