# Generated by Django 3.1.5 on 2021-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20210406_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            old_name='Manpower_Labour',
            new_name='Manpower',
        ),
        migrations.RemoveField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Manpower_Skilled',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Certificate_Date',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Recommendation',
        ),
        migrations.AddField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Desired_Inspection_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
