# Generated by Django 3.1.5 on 2021-07-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20210625_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Nationality',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
