# Generated by Django 3.1.5 on 2021-10-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_auto_20211023_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workflow_details',
            name='Applicant_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_details',
            name='Application_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_details_audit',
            name='Applicant_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_details_audit',
            name='Application_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
