# Generated by Django 3.1.5 on 2021-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20211026_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Entry_Point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
