# Generated by Django 3.1.5 on 2021-09-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20210914_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Nationality',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
