# Generated by Django 3.1.5 on 2021-03-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20210305_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Attachment',
            field=models.ImageField(upload_to='plant'),
        ),
    ]
