# Generated by Django 3.1.5 on 2021-07-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_auto_20210703_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_plant_import_permit_t1',
            name='Dzongkhag_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_import_permit_t1',
            name='Gewog_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_import_permit_t1',
            name='Village_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_movement_permit_t1',
            name='Dzongkhag_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_movement_permit_t1',
            name='Gewog_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_movement_permit_t1',
            name='Village_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Dzongkhag_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Gewog_Code',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Village_Code',
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='dzongkhag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='gewog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='village',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='dzongkhag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='gewog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='village',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='dzongkhag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='gewog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='village',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='dzongkhag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='gewog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='village',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
