# Generated by Django 3.1.5 on 2021-10-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_auto_20211026_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Exit_Point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Entry_Point',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
