# Generated by Django 3.1.5 on 2021-09-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_auto_20210914_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Nationality_Type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
