# Generated by Django 3.1.5 on 2021-07-27 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0007_auto_20210722_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_plant_movement_permit_t1',
            old_name='dzongkhag',
            new_name='Dzongkhag',
        ),
        migrations.RenameField(
            model_name='t_plant_movement_permit_t1',
            old_name='gewog',
            new_name='Gewog',
        ),
        migrations.RenameField(
            model_name='t_plant_movement_permit_t1',
            old_name='village',
            new_name='Village',
        ),
    ]
