# Generated by Django 3.1.5 on 2021-11-12 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20211028_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Additional_Declaration',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
