# Generated by Django 3.1.5 on 2021-07-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20210727_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            old_name='dzongkhag',
            new_name='Dzongkhag',
        ),
        migrations.RenameField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            old_name='gewog',
            new_name='Gewog',
        ),
        migrations.RenameField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            old_name='village',
            new_name='Village',
        ),
        migrations.RenameField(
            model_name='t_plant_seed_certification_t1',
            old_name='dzongkhag',
            new_name='Dzongkhag',
        ),
        migrations.RenameField(
            model_name='t_plant_seed_certification_t1',
            old_name='gewog',
            new_name='Gewog',
        ),
        migrations.RenameField(
            model_name='t_plant_seed_certification_t1',
            old_name='village',
            new_name='Village',
        ),
    ]
