# Generated by Django 3.1.5 on 2021-03-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_auto_20210305_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Attachment',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
