# Generated by Django 3.1.5 on 2021-11-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_t_plant_import_permit_t1_additional_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t2',
            name='Crop_Scientific_Name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
