# Generated by Django 3.1.5 on 2021-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_auto_20210727_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Unit_Area',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
