# Generated by Django 3.1.5 on 2021-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_auto_20210915_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_import_permit_inspection_t2',
            name='Quantity_Balance_1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
