# Generated by Django 3.1.5 on 2021-04-09 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_auto_20210408_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_plant_movement_permit_t1',
            old_name='Location_Code',
            new_name='From_Gewog_Code',
        ),
        migrations.AddField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Approved_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Validity',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Validity_Period',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Approved_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Validity',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Validity_Period',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Approved_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Validity',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Validity_Period',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='Approved_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='From_Location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='Validity',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='Validity_Period',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Approved_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Validity',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Validity_Period',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
