# Generated by Django 3.1.5 on 2021-03-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_auto_20210305_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_file_attachment',
            name='Attachment',
            field=models.FileField(upload_to='media/files/%Y-%m-%d'),
        ),
    ]
