# Generated by Django 3.1.5 on 2021-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20211112_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t2',
            name='Crop_Category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
