# Generated by Django 3.1.5 on 2021-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_t_plant_import_permit_inspection_t2_quantity_balance_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_seed_certification_t3',
            name='Record_Id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='t_plant_seed_certification_t3',
            name='Application_No',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
