# Generated by Django 3.1.5 on 2021-07-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20210728_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Dzongkhag',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Gewog',
        ),
        migrations.RemoveField(
            model_name='t_plant_seed_certification_t1',
            name='Village',
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Dzongkhag_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Gewog_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Location_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_seed_certification_t1',
            name='Village_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
