# Generated by Django 3.1.5 on 2021-03-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20210305_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='Nursery_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
