# Generated by Django 3.1.5 on 2021-04-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_auto_20210409_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_plant_movement_permit_t1',
            name='Name_And_Description',
        ),
    ]
