# Generated by Django 3.1.5 on 2021-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_auto_20210922_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Pieces_Gross',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Pieces_Net',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
