# Generated by Django 3.1.5 on 2021-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_remove_t_plant_movement_permit_t1_name_and_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='To_Gewog_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_movement_permit_t1',
            name='To_Location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='From_Dzongkhag_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='From_Gewog_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='To_Dzongkhag_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
