# Generated by Django 3.1.5 on 2021-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_auto_20210731_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Current_Observation',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Decision_Conformity',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
