# Generated by Django 3.1.5 on 2021-03-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_auto_20210313_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='Dzongkhag_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='Gewog_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='Village_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
