# Generated by Django 3.1.5 on 2021-11-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_auto_20211112_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_seed_certification_t2',
            name='Qty_Certified',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_seed_certification_t2',
            name='Quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
