# Generated by Django 3.1.5 on 2021-03-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_auto_20210313_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Place_Of_Entry',
            field=models.IntegerField(),
        ),
    ]
