# Generated by Django 3.1.5 on 2021-04-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_auto_20210409_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_movement_permit_t2',
            name='Unit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
