# Generated by Django 3.1.5 on 2021-11-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_auto_20211112_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Applicant_Id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='t_workflow_details_audit',
            name='Applicant_Id',
            field=models.CharField(max_length=100),
        ),
    ]
