# Generated by Django 3.1.5 on 2021-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_auto_20210410_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_payment_details',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=30)),
                ('Application_Date', models.DateField()),
                ('Permit_No', models.CharField(max_length=100)),
                ('Service_Id', models.CharField(max_length=5)),
                ('Validity', models.DateField()),
                ('Payment_Type', models.CharField(max_length=30)),
                ('Instrument_No', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('Receipt_No', models.CharField(max_length=30)),
                ('Receipt_Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='t_plant_clearence_nursery_seed_grower_t1',
            name='Validity',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Validity',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Validity',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_movement_permit_t1',
            name='Validity',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_seed_certification_t1',
            name='Validity',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
