# Generated by Django 3.1.5 on 2021-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_auto_20210315_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Field_Office_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
