# Generated by Django 3.1.5 on 2021-03-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0015_auto_20210315_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_details_audit',
            name='Action_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
