# Generated by Django 3.1.5 on 2021-04-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0015_auto_20210410_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_payment_details',
            name='Updated_By',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='Updated_On',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_payment_details',
            name='Amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_payment_details',
            name='Instrument_No',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_payment_details',
            name='Payment_Type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='t_payment_details',
            name='Receipt_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_payment_details',
            name='Receipt_No',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
