# Generated by Django 3.1.5 on 2021-04-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0016_auto_20210413_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Application_Status',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_details_audit',
            name='Application_Status',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
