# Generated by Django 3.1.5 on 2021-03-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0016_auto_20210315_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Action_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
