# Generated by Django 3.1.5 on 2021-03-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0017_auto_20210315_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Crop_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Pesticide_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Quantity_Released',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Remarks',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Variety_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
