# Generated by Django 3.1.5 on 2021-03-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0018_auto_20210315_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workflow_details',
            name='Assigned_Role_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_details_audit',
            name='Assigned_Role_Id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Assigned_To',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_details',
            name='Section',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_details_audit',
            name='Assigned_To',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_details_audit',
            name='Section',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
