# Generated by Django 3.1.5 on 2021-03-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0019_auto_20210317_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workflow_details',
            name='Service_Name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_details_audit',
            name='Service_Name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
