# Generated by Django 3.1.5 on 2021-03-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0021_t_plant_import_permit_t1_expected_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Application_No',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
