# Generated by Django 3.1.5 on 2021-03-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0022_auto_20210318_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_workflow_details',
            old_name='Service_Name',
            new_name='Service_Code',
        ),
    ]
