# Generated by Django 3.1.5 on 2021-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0023_auto_20210318_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='FO_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_import_permit_t1',
            name='Inspection_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
