# Generated by Django 3.1.5 on 2021-03-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0024_auto_20210319_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t2',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
