# Generated by Django 3.1.5 on 2021-03-29 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0026_t_plant_export_certificate_plant_plant_products_t1'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Additional_Information_Pre',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Chemical_Name_Pre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Concentration_Pre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Duration_Temperature_Pre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Pre_Application_Treatment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treated_By_Pre',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treated_Supervised_By_Pre',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Pre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
