# Generated by Django 3.1.5 on 2021-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0027_auto_20210329_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Other_Pre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Other_Treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
