# Generated by Django 3.1.5 on 2021-04-01 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0028_auto_20210329_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Inspection_Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Laboratory_Analysis_Comment',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Laboratory_Analysis_Required',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Permanent_Address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Chemical',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
