# Generated by Django 3.1.5 on 2021-04-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0029_auto_20210401_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Pieces_Gross',
            field=models.IntegerField(default=None),
        ),
    ]
