# Generated by Django 3.1.5 on 2021-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0030_t_plant_export_certificate_plant_plant_products_t1_pieces_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Applicant_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Business_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='CID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Contact_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Expected_Arrival_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Final_Destination',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='License_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Means_of_Conveyance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Name_And_Address_Supplier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Place_Of_Entry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Present_Address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_import_permit_t1',
            name='Purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
