# Generated by Django 3.1.5 on 2021-04-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0031_auto_20210401_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Additional_Declaring',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Additional_Information_Pre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Botanical_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='CID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Chemical_Name_Pre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Concentration_Pre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Consingee_Name_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Contact_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Duration_Temperature_Pre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Dzongkhag_Code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Entry_Point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Exporter_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Exporter_Name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Importing_Country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='License_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Locatipn_Code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Mode_Of_Conveyance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Name_Of_Conveyance',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Outlet_Address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Outlet_Contact_No',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Packages_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Packages_No',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Permanent_Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Pest_QR_Comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Pieces_Gross',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Pieces_Net',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Purpose_End_Use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Qty_Gross',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Qty_Net',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treated_By_Pre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treated_Supervised_By_Pre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Pre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Unit_Gross',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Unit_Net',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
