# Generated by Django 3.1.5 on 2021-04-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0032_auto_20210401_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Chemical',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Chemical_Name',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Chemical_Other',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Chemical_Seed',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_plant_export_certificate_plant_plant_products_t1',
            name='Treatment_Chemical_Spray',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
