# Generated by Django 3.1.5 on 2021-04-03 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0033_auto_20210402_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_file_attachment',
            name='File_Path',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
