# Generated by Django 3.1.5 on 2021-04-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_app_status_master',
            fields=[
                ('Status_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Status_Name', models.CharField(max_length=100)),
                ('Status_Type', models.CharField(max_length=20)),
                ('Status_Type_Short_Desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='t_country_master',
            fields=[
                ('Country_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Country_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_division_master',
            fields=[
                ('Division_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Division_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_dzongkhag_master',
            fields=[
                ('Dzongkhag_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Dzongkhag_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_field_office_master',
            fields=[
                ('Field_Office_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Field_Office_Code', models.CharField(default=None, max_length=3)),
                ('Field_Office', models.CharField(max_length=100)),
                ('Is_Entry_Point', models.CharField(blank=True, choices=[('Y', 'Y'), ('N', 'N')], default=None, max_length=1, null=True)),
                ('Remarks', models.CharField(max_length=250)),
                ('Dzongkhag_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_dzongkhag_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_forgot_password',
            fields=[
                ('Forgot_Pass_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Login_Id', models.IntegerField()),
                ('Security_Question_Id', models.IntegerField()),
                ('Answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='t_gewog_master',
            fields=[
                ('Gewog_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Gewog_Name', models.CharField(max_length=100)),
                ('Dzongkhag_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_dzongkhag_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_chemical_master',
            fields=[
                ('Chemical_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Chemical_Type', models.TextField()),
                ('Chemical_Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_crop_category_master',
            fields=[
                ('Crop_Category_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Crop_Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_crop_master',
            fields=[
                ('Crop_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Crop_Common_Name', models.CharField(max_length=100)),
                ('Crop_Scientific_Name', models.CharField(max_length=100)),
                ('Crop_Category_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_plant_crop_category_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_crop_species_master',
            fields=[
                ('Crop_Species_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Species_Common_Name', models.CharField(max_length=100)),
                ('Species_Scientific_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_fodder_master',
            fields=[
                ('Fodder_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fodder_Common_Name', models.CharField(max_length=100)),
                ('Fodder_Scientific_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_ornamental_master',
            fields=[
                ('Ornamental_Plant_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Ornamental_Common_Name', models.CharField(max_length=100)),
                ('Ornamental_Scientific_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_pesticide_master',
            fields=[
                ('Pesticide_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Pesticide_Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_product_master',
            fields=[
                ('Plant_Product_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Plant_Product_Name', models.CharField(max_length=100)),
                ('Product_Scientific_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_role_master',
            fields=[
                ('Role_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_section_master',
            fields=[
                ('Section_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Section_Name', models.CharField(max_length=100)),
                ('Division_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_division_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_security_question_master',
            fields=[
                ('Question_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_service_master',
            fields=[
                ('Service_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Service_Name', models.CharField(max_length=100)),
                ('Service_Code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_user_type_master',
            fields=[
                ('User_Type_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='t_village_master',
            fields=[
                ('Village_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Village_Name', models.CharField(max_length=100)),
                ('Gewog_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_gewog_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_user_master',
            fields=[
                ('Login_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Login_Type', models.TextField(blank=True, default=None, null=True)),
                ('Client_Type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Employee_Id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('Mobile_Number', models.IntegerField(blank=True, default=None, null=True)),
                ('Email_Id', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('Password', models.TextField(blank=True, default=None, null=True)),
                ('Password_Salt', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('CID', models.BigIntegerField(blank=True, default=None, null=True)),
                ('Agency', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('License_No', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Address', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('Is_Active', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('Logical_Delete', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('Last_Login_Date', models.DateField(blank=True, default=None, null=True)),
                ('Created_By', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Created_On', models.DateField(blank=True, default=None, null=True)),
                ('Updated_By', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Updated_On', models.DateField(blank=True, default=None, null=True)),
                ('Accept_Reject', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('Division_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_division_master')),
                ('Dzongkhag_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_dzongkhag_master')),
                ('Field_Office_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_field_office_master')),
                ('Gewog_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_gewog_master')),
                ('Role_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_role_master')),
                ('Section_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_section_master')),
                ('Village_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_village_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_fodder_variety_master',
            fields=[
                ('Fodder_Variety_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Fodder_Variety_Name', models.CharField(max_length=100)),
                ('Fodder_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_plant_fodder_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_plant_crop_variety_master',
            fields=[
                ('Crop_Variety_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Crop_Variety_Name', models.CharField(max_length=100)),
                ('Crop_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_plant_crop_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_location_field_office_mapping',
            fields=[
                ('Location_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Location_Name', models.CharField(max_length=100)),
                ('Dzongkhag_Code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_dzongkhag_master')),
                ('Field_Office_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.t_field_office_master')),
            ],
        ),
    ]
