# Generated by Django 3.1.7 on 2021-04-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_plant_crop_category_master',
            fields=[
                ('Crop_Category_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Crop_Category_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
