# Generated by Django 3.1.5 on 2021-12-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_village_master',
            name='Village_Name_Dzo',
        ),
    ]
