# Generated by Django 3.1.5 on 2021-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_unit_master',
            fields=[
                ('Unit_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Unit', models.CharField(max_length=20)),
            ],
        ),
    ]
