# Generated by Django 3.1.5 on 2021-12-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_village_master',
            name='Village_Name_Dzo',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
