# Generated by Django 3.1.5 on 2021-05-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_t_inspection_type_master'),
    ]

