# Generated by Django 3.1.5 on 2022-01-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_field_office_master',
            name='Conveyance_Means',
            field=models.CharField(blank=True, choices=[('By Road', 'By Road'), ('By Air', 'By Air')], default=None, max_length=20, null=True),
        ),
    ]
