# Generated by Django 3.1.5 on 2021-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_t_food_category_master_t_livestock_category_master_t_livestock_product_master_t_livestock_species_br'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user_master',
            name='Is_Officiating',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
    ]
