# Generated by Django 3.1.5 on 2022-04-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_t_field_office_master_conveyance_means'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_meat_item_master',
            old_name='Item_Code',
            new_name='item_code',
        ),
        migrations.RenameField(
            model_name='t_meat_item_master',
            old_name='Meat_Item',
            new_name='meat_item',
        ),
    ]
