# Generated by Django 3.1.5 on 2021-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_t_user_master_is_officiating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_user_master',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_user_master',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_user_master',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
