# Generated by Django 3.1.7 on 2021-08-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_t_user_master_is_officiating'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_village_master',
            name='Village_Name_Dzo',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
