# Generated by Django 3.1.5 on 2021-09-01 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20210802_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_meat_item_master',
            fields=[
                ('Item_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Meat_Item', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='t_village_master',
            name='Village_Name_Dzo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
