# Generated by Django 3.1.7 on 2021-09-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20210901_1037'),

    ]

    operations = [
    ]
