# Generated by Django 3.1.7 on 2021-09-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_merge_20210907_0916'),
    ]

    operations = [



        migrations.AlterField(
            model_name='t_user_master',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_user_master',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_user_master',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),


    ]
