# Generated by Django 3.1.5 on 2021-11-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_auto_20210907_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_unit_master',
            name='Unit_Type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
