# Generated by Django 3.1.7 on 2021-04-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_common_complaint_t1',
            fields=[
                ('Application_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('CID', models.BigIntegerField()),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Village_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Contact_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(blank=True, max_length=250, null=True)),
                ('Complaint_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Complaint_Description', models.TextField(blank=True, null=True)),
                ('Acknowledge', models.CharField(blank=True, max_length=1, null=True)),
                ('Assign_To', models.CharField(blank=True, max_length=100, null=True)),
                ('Assign_Date', models.DateField(blank=True, null=True)),
                ('Assign_Remarks', models.TextField(blank=True, null=True)),
                ('Investigation_Date', models.DateField(blank=True, null=True)),
                ('Investigation_By', models.TextField(blank=True, null=True)),
                ('Investigation_Report', models.TextField(blank=True, null=True)),
                ('Report_Submit_Date', models.DateField(blank=True, null=True)),
                ('Closure_Date', models.DateField(blank=True, null=True)),
                ('Closure_Remarks', models.TextField(blank=True, null=True)),
                ('Application_Status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
