# Generated by Django 3.1.5 on 2022-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_feebback',
            name='Service',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
