# Generated by Django 3.1.7 on 2021-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_common_complaint_t1',
            name='Acknowledge_Date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_common_complaint_t1',
            name='Acknowledge_Remarks',
            field=models.TextField(default=None, null=True),
        ),
    ]
