# Generated by Django 3.1.7 on 2021-05-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0002_auto_20210519_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_common_complaint_t1',
            name='Acknowledge',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
