# Generated by Django 3.1.5 on 2022-01-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0002_t_feebback_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_feebback',
            name='Service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
