# Generated by Django 3.1.5 on 2022-01-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0003_auto_20220126_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_feebback',
            name='Service_Code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
