# Generated by Django 3.1.5 on 2021-05-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0002_t_inspection_monitoring_t1_t_inspection_monitoring_t2_t_inspection_monitoring_t3_t_inspection_monito'),
        ('common_service', '0003_auto_20210523_1045'),
    ]

    operations = [
    ]
