# Generated by Django 3.1.5 on 2021-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0005_auto_20210524_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_inspection_monitoring_t4',
            name='Collection_Type',
        ),
        migrations.AddField(
            model_name='t_inspection_monitoring_t3',
            name='Detaintion_Destruction_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
