# Generated by Django 3.1.5 on 2021-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0006_auto_20210524_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_inspection_monitoring_t1',
            name='Application_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_inspection_monitoring_t1',
            name='Service_Code',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
