# Generated by Django 3.1.5 on 2021-05-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0007_auto_20210524_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_inspection_monitoring_t1',
            name='Application_Date',
        ),
    ]
