# Generated by Django 3.1.7 on 2021-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0008_remove_t_inspection_monitoring_t1_application_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_commodity_inspection_t1',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(blank=True, max_length=30, null=True)),
                ('FBO_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Registration_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Dzongkhag_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Gewog_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Village_Code', models.CharField(blank=True, max_length=10, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_No', models.IntegerField(blank=True, null=True)),
                ('Inspection_Date', models.DateField(blank=True, default=None, null=True)),
                ('Inspection_Team', models.TextField(blank=True, null=True)),
                ('Team_Leader', models.IntegerField(blank=True, null=True)),
                ('Commodity', models.TextField(blank=True, default=None, null=True)),
                ('Purpose', models.TextField(blank=True, default=None, null=True)),
                ('Observation', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_commodity_inspection_t2',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(blank=True, max_length=30, null=True)),
                ('Commodity', models.CharField(blank=True, max_length=250, null=True)),
                ('Commodity_Requirement', models.CharField(blank=True, max_length=250, null=True)),
                ('Qty_Inspected', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, max_length=10, null=True)),
                ('Qty_Cleared', models.IntegerField(blank=True, null=True)),
                ('Qty_Rejected', models.IntegerField(blank=True, null=True)),
                ('Reason_For_Rejection', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
