# Generated by Django 3.1.7 on 2021-06-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0010_auto_20210601_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_commodity_inspection_t1',
            old_name='Created_On',
            new_name='Created_Date',
        ),
    ]
