# Generated by Django 3.1.7 on 2021-06-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0011_auto_20210602_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_inspection_monitoring_t1',
            name='Observation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_commodity_inspection_t1',
            name='Created_By',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
