# Generated by Django 3.1.7 on 2021-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0012_auto_20210604_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_inspection_monitoring_t3',
            old_name='Detaintion_Destruction_No',
            new_name='Detention_Destruction_No',
        ),
        migrations.RenameField(
            model_name='t_inspection_monitoring_t4',
            old_name='Batch_No_Date',
            new_name='Batch_No',
        ),
        migrations.AddField(
            model_name='t_inspection_monitoring_t4',
            name='Batch_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_commodity_inspection_t1',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_commodity_inspection_t2',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t1',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t2',
            name='Correction_Proposed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t2',
            name='Correction_Taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t2',
            name='Inspector_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t2',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t2',
            name='Revenue_Receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t3',
            name='Inspector_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t3',
            name='Items_Seized',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t3',
            name='Reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t3',
            name='Revenue_Receipt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t3',
            name='Unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t4',
            name='Reference_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t4',
            name='Test_Report',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t4',
            name='Test_Requested',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
