# Generated by Django 3.1.7 on 2021-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0013_auto_20210604_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_inspection_monitoring_t1',
            name='Application_Flag',
        ),
        migrations.AddField(
            model_name='t_inspection_monitoring_t1',
            name='Created_By',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_inspection_monitoring_t1',
            name='Created_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
