# Generated by Django 3.1.7 on 2021-06-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0014_auto_20210604_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_inspection_monitoring_t4',
            name='Collection_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
