# Generated by Django 3.1.7 on 2021-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0016_t_feebback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_feebback',
            name='Created_By',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
