# Generated by Django 3.1.7 on 2021-07-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_service', '0017_auto_20210702_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_feebback',
            name='Feedback_Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
