# Generated by Django 3.1.5 on 2021-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_livestock_clearence_meat_shop_t1',
            fields=[
                ('Application_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(blank=True, max_length=100, null=True)),
                ('Scope', models.CharField(default=None, max_length=20)),
                ('Purpose', models.CharField(default=None, max_length=100)),
                ('Name_Meat_Shop', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Ownership_Type', models.CharField(default=None, max_length=100)),
                ('CID', models.BigIntegerField()),
                ('Name_Owner', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Village_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Location_Code', models.IntegerField()),
                ('Establish_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Establishment_Size', models.CharField(blank=True, max_length=200, null=True)),
                ('Meat_Type', models.CharField(blank=True, max_length=200, null=True)),
                ('Clearance_Type', models.CharField(blank=True, max_length=10, null=True)),
                ('Any_Proceedings', models.CharField(blank=True, max_length=10, null=True)),
                ('Reason_Suspension', models.TextField(blank=True, null=True)),
                ('Desired_Inspection_Date', models.DateField(blank=True, null=True)),
                ('Resubmit_Date', models.DateField(blank=True, null=True)),
                ('Desired_Reinspection_Date', models.DateField(blank=True, null=True)),
                ('Remarks_Reinspection', models.TextField(blank=True, null=True)),
                ('Inspection_Date', models.DateField(blank=True, null=True)),
                ('Remarks_Inspection', models.TextField(blank=True, null=True)),
                ('Inspection_Leader', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Inspection_Team', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Application_Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('Meat_Shop_Clearance_No', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Conformity', models.CharField(blank=True, max_length=10, null=True)),
                ('Conformity_Statement', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_livestock_clearence_meat_shop_t2',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Inspection_Type', models.CharField(max_length=20)),
                ('Observation', models.TextField(blank=True, null=True)),
                ('Action', models.TextField(blank=True, null=True)),
                ('Time_Line', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
