# Generated by Django 3.1.5 on 2021-06-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_livestock_clearance_meat_shop_t2',
            old_name='BP_Outsourced_To',
            new_name='Meat_Item',
        ),


        migrations.AddField(
            model_name='t_livestock_movement_permit_t1',
            name='Application_Type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_export_certificate_t1',
            name='Application_Type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Application_Type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Application_Type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Application_Type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_t1',
            name='Application_Type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
