# Generated by Django 3.1.7 on 2021-04-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_livestock_ante_post_mortem_t1',
            old_name='Application_Type',
            new_name='Inspection_Type',
        ),
        migrations.RenameField(
            model_name='t_livestock_export_certificate_t1',
            old_name='Export_Type',
            new_name='Exporter_Type',
        ),
        migrations.RemoveField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Purpose',
        ),
        migrations.RemoveField(
            model_name='t_livestock_import_permit_product_t1',
            name='Purpose',
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Colour',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Gait',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Odour',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Posture',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Behaviour_Abnormalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Discharge_Abnormalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Inspection_Date_Requested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Close_Supervision',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Emergency',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Unfit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Withheld',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Without_Restrictions',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Respiration_Abnormalities',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_export_certificate_t1',
            name='Applicant_Id',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_export_certificate_t2',
            name='No_Of_Animal',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_export_certificate_t2',
            name='Unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Quarantine_Facilities',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t2',
            name='Product_Record_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t2',
            name='Quantity_Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Import_Permit_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Quarantine_Facilities',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Product_Record_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Quantity_Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_t1',
            name='Import_Permit_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_movement_permit_t2',
            name='No_Of_Animal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Company_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Particulars',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_t2',
            name='Company_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_t2',
            name='Particulars',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t1',
            name='Permit_Type',
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t2',
            name='Company_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t2',
            name='Particulars',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
