# Generated by Django 3.1.5 on 2022-01-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t4',
            name='Closing_Meeting_Date',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t4',
            name='Open_Meeting_Date',
        ),
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t4',
            name='Meeting_Date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t4',
            name='Type',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
