# Generated by Django 3.1.5 on 2021-04-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Location_Code',
        ),
        migrations.AddField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Approved_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Validity',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Validity_Period',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
