# Generated by Django 3.1.5 on 2021-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_t2',
            name='Breed',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_t2',
            name='Species',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
