# Generated by Django 3.1.7 on 2021-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Any_Proceedings',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Clearance_Type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Establish_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Establishment_Size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Meat_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Name_Owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
