# Generated by Django 3.1.5 on 2021-10-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Behaviour_Abnormalities',
        ),
        migrations.RemoveField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Discharge_Abnormalities',
        ),
        migrations.RemoveField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities',
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Behaviour_Abnormalities_1',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Behaviour_Abnormalities_2',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Behaviour_Abnormalities_3',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Behaviour_Abnormalities_4',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Discharge_Abnormalities_1',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Discharge_Abnormalities_2',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Discharge_Abnormalities_3',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities_1',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities_2',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities_3',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities_4',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities_5',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities_6',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
