# Generated by Django 3.1.5 on 2021-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20211004_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t5',
            name='NC',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t5',
            name='NC_Category',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
