# Generated by Django 3.1.5 on 2021-04-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20210414_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_livestock_ante_post_mortem_t1',
            old_name='Application_Type',
            new_name='Inspection_Type',
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Inspection_Date_Requested',
            field=models.DateField(blank=True, null=True),
        ),
    ]
