# Generated by Django 3.1.7 on 2021-04-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20210412_1135'),
        ('livestock', '0002_t_livestock_export_certificate_t1_t_livestock_export_certificate_t2_t_livestock_export_certificate_t'),
    ]

    operations = [
    ]
