# Generated by Django 3.1.5 on 2021-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20210412_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Conformity',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Conformity_Statement',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t2',
            name='Inspection_Type',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t2',
            name='Time_Line',
        ),
        migrations.AddField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Identification_No',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Inspection_Type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Revision_No',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
