# Generated by Django 3.1.5 on 2021-09-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20210816_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='FI_Inspection_Team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='FR_Inspection_Team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
