# Generated by Django 3.1.7 on 2021-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20210424_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
