# Generated by Django 3.1.5 on 2021-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20210625_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Business_Name',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Current_Status',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='FBO_Judicial_Proceedings',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='FBO_License_No',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='FBO_License_Status',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='FBO_Regulatory_Proceedings',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Invalid_Reason',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Judicial_Proceedings_Details',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Large_Corporation',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Large_Corporation_Relation',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Legal_Entity',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Previous_Business',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Process_Outsource',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Product_Category',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Project_Proposal',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Regulatory_Proceedings_Details',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Site_History',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Volume_Last_Year',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Volume_Unit',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Water_Source',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Years_In_Production',
        ),
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Representative',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Village_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
