# Generated by Django 3.1.5 on 2021-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20210625_1640'),
    ]

    operations = [

        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Representative',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),

    ]
