# Generated by Django 3.1.7 on 2021-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_merge_20210413_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_livestock_ante_post_mortem_t1',
            fields=[
                ('Application_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Application_Type', models.CharField(default=None, max_length=1)),
                ('CID', models.BigIntegerField()),
                ('Applicant_Name', models.CharField(max_length=250)),
                ('Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Village_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Address', models.TextField(blank=True, default=None, null=True)),
                ('Contact_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Location_Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Location_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Exact_Location', models.TextField(blank=True, default=None, null=True)),
                ('Inspection_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Leader', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Inspection_Team', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Application_Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('Clearance_No', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(max_length=100)),
                ('Approved_Date', models.DateField(blank=True, default=None, null=True)),
                ('Validity_Period', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Validity', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_livestock_ante_post_mortem_t2',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Species', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Nos', models.IntegerField(blank=True, default=None, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_livestock_movement_permit_t1',
            fields=[
                ('Application_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Permit_Type', models.CharField(default=None, max_length=1)),
                ('CID', models.BigIntegerField()),
                ('Applicant_Name', models.CharField(max_length=250)),
                ('Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Village_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Contact_No', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('License_No', models.CharField(max_length=100)),
                ('Business_Name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('From_Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('From_Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('From_Location', models.CharField(max_length=100)),
                ('To_Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('To_Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('To_Location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Authorized_Route', models.CharField(max_length=100)),
                ('Movement_Purpose', models.CharField(max_length=100)),
                ('Conveyance_Means', models.CharField(max_length=20)),
                ('Vehicle_No', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Movement_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Leader', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Inspection_Team', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Application_Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('Movement_Permit_No', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(max_length=100)),
                ('Approved_Date', models.DateField(blank=True, default=None, null=True)),
                ('Validity_Period', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Validity', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_livestock_movement_permit_t2',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Common_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Scientific_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Particulars', models.IntegerField(blank=True, null=True)),
                ('Company_Name', models.IntegerField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity_Released', models.IntegerField(blank=True, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_livestock_movement_permit_t3',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=20)),
                ('Current_Observation', models.TextField()),
                ('Decision_Conformity', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Approved_Date',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Validity',
        ),
        migrations.RemoveField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Validity_Period',
        ),
    ]
