# Generated by Django 3.1.7 on 2021-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20210511_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Applicant_Id',
        ),
        migrations.RemoveField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Applicant_Id',
        ),
        migrations.RemoveField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Applicant_Id',
        ),
        migrations.RemoveField(
            model_name='t_livestock_import_permit_product_t1',
            name='Applicant_Id',
        ),
        migrations.AlterField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
