# Generated by Django 3.1.5 on 2021-04-16 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20210415_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_export_certificate_t1',
            name='Applicant_Id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_livestock_movement_permit_t2',
            name='No_Of_Animal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t1',
            name='Permit_Type',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
