# Generated by Django 3.1.5 on 2021-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20210413_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_clearence_meat_shop_t1',
            name='Application_Status',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
