# Generated by Django 3.1.5 on 2021-09-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20210909_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_livestock_clearance_meat_shop_t1',
            old_name='FB_License_No',
            new_name='Meat_Shop_Clearance_No',
        ),
    ]
