# Generated by Django 3.1.5 on 2022-04-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20220412_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_livestock_clearance_meat_shop_t5',
            old_name='fbo_Response',
            new_name='fbo_response',
        ),
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='application_source',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
