# Generated by Django 3.1.5 on 2021-11-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20211023_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_export_certificate_t2',
            name='Species',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
