# Generated by Django 3.1.5 on 2021-06-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20210625_1707'),
    ]

    operations = [

        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Meat_Shop_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
