# Generated by Django 3.1.5 on 2021-06-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20210626_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Application_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
