# Generated by Django 3.1.5 on 2021-04-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20210416_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_export_certificate_t2',
            name='No_Of_Animal',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
