# Generated by Django 3.1.5 on 2021-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20210910_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t2',
            name='Quantity_Balance_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Quantity_Balance_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_export_certificate_t2',
            name='Company_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
