# Generated by Django 3.1.5 on 2021-11-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20211110_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_t2',
            name='Species',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
