# Generated by Django 3.1.5 on 2021-07-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_auto_20210626_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_clearance_meat_shop_t1',
            name='Location_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_export_certificate_t1',
            name='Passport_No',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_export_certificate_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_export_certificate_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_export_certificate_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_inspection_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
