# Generated by Django 3.1.7 on 2021-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_auto_20210626_0942'),
    ]

    operations = [

    ]
