# Generated by Django 3.1.5 on 2021-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_t_livestock_export_certificate_t2_no_of_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_livestock_import_permit_product_inspection_t1',
            name='Import_Permit_No',
        ),
        migrations.RemoveField(
            model_name='t_livestock_import_permit_product_t1',
            name='Purpose',
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_t1',
            name='Import_Permit_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
