# Generated by Django 3.1.5 on 2021-11-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_auto_20211110_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_import_permit_animal_inspection_t2',
            name='Species',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
