# Generated by Django 3.1.5 on 2021-04-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_auto_20210419_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Quarantine_Facilities',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
