# Generated by Django 3.1.7 on 2021-08-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0006_auto_20210731_1002'),
        ('livestock', '0008_auto_20210726_0522'),
    ]

    operations = [
    ]
