# Generated by Django 3.1.5 on 2021-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0011_auto_20210420_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Company_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Particulars',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
