# Generated by Django 3.1.5 on 2021-04-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0012_auto_20210420_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t2',
            name='Quantity_Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Quantity_Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
