# Generated by Django 3.1.5 on 2021-04-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_auto_20210420_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_inspection_t2',
            name='Product_Record_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_import_permit_product_inspection_t2',
            name='Product_Record_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
