# Generated by Django 3.1.5 on 2021-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_t_livestock_export_certificate_t2_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Colour',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Gait',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Odour',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Abnormal_Posture',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Behaviour_Abnormalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Discharge_Abnormalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Close_Supervision',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Emergency',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Unfit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Withheld',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='No_Without_Restrictions',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Respiration_Abnormalities',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_livestock_ante_post_mortem_t1',
            name='Structure_Abnormalities',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
