# Generated by Django 3.1.5 on 2021-04-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0016_auto_20210422_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_livestock_import_permit_animal_t1',
            name='Import_Permit_No',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
