# Generated by Django 3.1.5 on 2021-04-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0017_t_livestock_import_permit_animal_t1_import_permit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t2',
            name='Company_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_livestock_movement_permit_t2',
            name='Particulars',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
