# Generated by Django 3.1.5 on 2021-04-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_food_export_certificate_t1',
            fields=[
                ('Application_No', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('License_No', models.CharField(blank=True, max_length=100, null=True)),
                ('CID', models.BigIntegerField(blank=True, null=True)),
                ('Exporters_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Village_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Exporters_Address', models.TextField(blank=True, null=True)),
                ('Contact_No', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Importer_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Importer_Address', models.TextField(blank=True, null=True)),
                ('Importing_Country', models.IntegerField(blank=True, default=None, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('No_Of_Packages', models.IntegerField(blank=True, null=True)),
                ('Description_Of_Packages', models.TextField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Declared_Point_of_Exit', models.IntegerField(blank=True, null=True)),
                ('Export_Expected_Date', models.DateField(blank=True, null=True)),
                ('Proposed_Inspection_Date', models.DateField(blank=True, null=True)),
                ('Purpose_Of_Export', models.TextField(blank=True, null=True)),
                ('Consignment_Location_Dzongkhag', models.IntegerField(blank=True, null=True)),
                ('Consignment_Location_Gewog', models.IntegerField(blank=True, null=True)),
                ('Consignment_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Additional_Information', models.TextField(blank=True, default=None, null=True)),
                ('Inspection_Date', models.DateField(blank=True, null=True)),
                ('Inspection_Leader', models.CharField(blank=True, max_length=100, null=True)),
                ('Inspection_Team', models.TextField(blank=True, null=True)),
                ('Inspection_Remarks', models.TextField(blank=True, null=True)),
                ('Quantity_Certified', models.IntegerField(blank=True, null=True)),
                ('Unit_Certified', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity_Rejected', models.IntegerField(blank=True, null=True)),
                ('Unit_Rejected', models.CharField(blank=True, max_length=100, null=True)),
                ('Export_Permit_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Approved_Date', models.DateField(blank=True, null=True)),
                ('Validity_Period', models.IntegerField(blank=True, null=True)),
                ('Validity', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_food_licensinf_food_handler_t1',
            fields=[
                ('Application_No', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Application_Date', models.DateField(blank=True, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('CID', models.BigIntegerField(blank=True, null=True)),
                ('Permit_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Applicant_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Dzongkhag_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Gewog_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Village_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Country_Code', models.IntegerField(blank=True, default=None, null=True)),
                ('Contact_No', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Training_Request', models.CharField(blank=True, max_length=250, null=True)),
                ('Preferred_Inspection_Place', models.TextField(blank=True, null=True)),
                ('Proposed_Inspection_Date', models.DateField(blank=True, null=True)),
                ('Associated_Food_Establishment', models.TextField(blank=True, null=True)),
                ('Training_Batch_No', models.CharField(blank=True, max_length=100, null=True)),
                ('Training_Date', models.DateField(blank=True, null=True)),
                ('License_Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Assessment_Score', models.IntegerField(blank=True, null=True)),
                ('Minimum_Score', models.IntegerField(blank=True, null=True)),
                ('Trainer', models.CharField(blank=True, max_length=100, null=True)),
                ('FH_License_No', models.CharField(blank=True, max_length=20, null=True)),
                ('Approved_Date', models.DateField(blank=True, null=True)),
                ('FH_License_Validity_Period', models.IntegerField(blank=True, null=True)),
                ('FH_License_Validity', models.DateField(blank=True, null=True)),
                ('Applicant_Id', models.CharField(max_length=100)),
                ('OIC_Remarks', models.TextField(blank=True, default=None, null=True)),
                ('Inspection_Remarks', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
