# Generated by Django 3.1.5 on 2022-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_food_business_registration_licensing_t7',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=100)),
                ('Source_Country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='t_food_business_registration_licensing_t8',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=100)),
                ('Source_Country', models.CharField(max_length=30)),
            ],
        ),
    ]
