# Generated by Django 3.1.5 on 2022-01-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_t_food_business_registration_licensing_t7_t_food_business_registration_licensing_t8'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='Process_Flow_Technology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='Quality_Assurance_System',
            field=models.TextField(blank=True, null=True),
        ),
    ]
