# Generated by Django 3.1.5 on 2022-01-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20220120_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t4',
            old_name='Closing_Meeting_Date',
            new_name='Meeting_Date',
        ),
        migrations.RemoveField(
            model_name='t_food_business_registration_licensing_t4',
            name='Open_Meeting_Date',
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t4',
            name='Type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
