# Generated by Django 3.1.5 on 2021-10-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20211014_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_food_import_permit_t1',
            name='Origin_Country_Food',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
