# Generated by Django 3.1.5 on 2021-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210428_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_licensinf_food_handler_t1',
            name='Attendance',
            field=models.CharField(blank=True, default='No', max_length=5, null=True),
        ),
    ]
