# Generated by Django 3.1.5 on 2022-04-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20220124_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_export_certificate_t1',
            name='Application_Type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
