# Generated by Django 3.1.5 on 2021-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_t_food_import_permit_inspection_t1_t_food_import_permit_inspection_t2_t_food_import_permit_inspectio'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_import_permit_inspection_t2',
            name='Product_Record_Id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
