# Generated by Django 3.1.5 on 2022-04-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20220412_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t1',
            old_name='FBO_License_Status',
            new_name='fbo_license_status',
        ),
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t1',
            old_name='fi_inspection_Leader',
            new_name='fi_inspection_leader',
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='application_source',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
