# Generated by Django 3.1.5 on 2021-05-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_t_food_business_registration_licensing_t1_t_food_business_registration_licensing_t2_t_food_business_'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='FH_License_No',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='FH_Name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='Volume_Unit',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
