# Generated by Django 3.1.5 on 2022-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20220418_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t1',
            old_name='FBO_License_No',
            new_name='fbo_license_no',
        ),
        migrations.AddField(
            model_name='t_food_export_certificate_t1',
            name='Batch_No',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_food_export_certificate_t1',
            name='Expiry_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_food_export_certificate_t1',
            name='Mfd_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
