# Generated by Django 3.1.5 on 2021-05-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20210504_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t2',
            old_name='Contact_No_Address',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='t_food_business_registration_licensing_t1',
            name='FH_License_No',
        ),
        migrations.RemoveField(
            model_name='t_food_business_registration_licensing_t1',
            name='FH_Name',
        ),
        migrations.RemoveField(
            model_name='t_food_business_registration_licensing_t2',
            name='Process_Outsourced',
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t2',
            name='Contact_No',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='t_food_business_registration_licensing_t2',
            name='BAFRA_License_No',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
