# Generated by Django 3.1.5 on 2021-05-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210504_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_food_business_registration_licensing_t2',
            name='Record_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='t_food_business_registration_licensing_t3',
            name='Record_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='t_food_business_registration_licensing_t4',
            name='Record_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='t_food_business_registration_licensing_t5',
            name='Record_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
