# Generated by Django 3.1.5 on 2021-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20210505_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_food_business_registration_licensing_t6',
            fields=[
                ('Record_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Application_No', models.CharField(max_length=30)),
                ('Meeting_Type', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=30)),
            ],
        ),
    ]
