# Generated by Django 3.1.5 on 2021-05-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_t_food_business_registration_licensing_t1_field_office_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t1',
            old_name='Desired_Inspection_Date',
            new_name='Desired_FI_Inspection_Date',
        ),
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t1',
            old_name='FI_Inspection_Team',
            new_name='FI_Response',
        ),
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t1',
            old_name='FR_Inspection_Team',
            new_name='FR_Recommendation',
        ),
        migrations.RemoveField(
            model_name='t_food_business_registration_licensing_t1',
            name='Remarks_Inspection',
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='Desired_FR_Inspection_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='FR_Response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
