# Generated by Django 3.1.5 on 2021-05-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20210507_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_food_business_registration_licensing_t5',
            name='Concern',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
