# Generated by Django 3.1.7 on 2021-05-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20210507_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_import_permit_inspection_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='t_food_import_permit_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_export_certificate_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_licensinf_food_handler_t1',
            name='Applicant_Id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
