# Generated by Django 3.1.7 on 2021-05-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20210511_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t_food_licensinf_food_handler_t1',
            new_name='t_food_licensing_food_handler_t1',
        ),
    ]
