# Generated by Django 3.1.5 on 2021-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_auto_20210525_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_food_import_permit_inspection_t2',
            name='Product_Name_Description',
        ),
        migrations.AddField(
            model_name='t_food_import_permit_inspection_t2',
            name='Common_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_food_import_permit_inspection_t2',
            name='Product_Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_food_import_permit_inspection_t2',
            name='Product_Characteristics',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_import_permit_inspection_t2',
            name='Exporter_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
