# Generated by Django 3.1.5 on 2021-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_auto_20210525_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_import_permit_inspection_t1',
            name='Terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_food_import_permit_t1',
            name='Terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
