# Generated by Django 3.1.5 on 2021-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_auto_20210525_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='Dzongkhag_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='Gewog_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
