# Generated by Django 3.1.5 on 2021-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_auto_20210525_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_food_business_registration_licensing_t5',
            old_name='Meeting_Type',
            new_name='Inspection_Type',
        ),
        migrations.AddField(
            model_name='t_food_export_certificate_t1',
            name='Rejection_Reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
