# Generated by Django 3.1.5 on 2021-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0024_auto_20210525_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_export_certificate_t1',
            name='Terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_food_licensing_food_handler_t1',
            name='Training_Batch',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_food_licensing_food_handler_t1',
            name='Training_Venue',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
