# Generated by Django 3.1.5 on 2021-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0025_auto_20210525_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_food_licensing_food_handler_t1',
            name='Attendance',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
