# Generated by Django 3.1.5 on 2021-06-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0026_auto_20210630_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_licensing_food_handler_t1',
            name='App_Status',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
