# Generated by Django 3.1.5 on 2021-07-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_t_food_licensing_food_handler_t1_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_food_business_registration_licensing_t1',
            name='Years_In_Production',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
