# Generated by Django 3.1.5 on 2021-07-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_auto_20210720_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_food_business_registration_licensing_t1',
            name='Village_Code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_export_certificate_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_export_certificate_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_export_certificate_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_import_permit_inspection_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_import_permit_inspection_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_import_permit_inspection_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_import_permit_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_import_permit_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_import_permit_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_licensing_food_handler_t1',
            name='Dzongkhag_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_licensing_food_handler_t1',
            name='Gewog_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_food_licensing_food_handler_t1',
            name='Village_Code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
